eclipse-gef/gef-classic

.github/.github/workflows/maven.yml
=> Adds GH build action

README.md
Replaced all GEF legacy mentions with GEF classic. Updated the target
platform and fixed some minor typos.
=> [Issue #20] Cleaned-up README.md

Jenkinsfile
Currently without creating the update site
=> Adds Jenkins file to repo

Jenkinsfile, pom.xml
I copied the profile from platform and added it to the main pom for GEF.
Unfortunately AFAIK this cannot be tested locally.
=> Adding signing to the build, similar as platform does it

.github/workflows/dependabot.yml
With this change @dependabot on Github will create PRs for these updates
if available
=> Adding dependabot check to GEF

org.eclipse.draw2d-feature/feature.xml, org.eclipse.draw2d.sdk-feature/feature.xml, org.eclipse.gef-feature/feature.xml, org.eclipse.gef.examples-feature/feature.xml, org.eclipse.gef.sdk-feature/feature.xml, org.eclipse.zest-feature/feature.xml, org.eclipse.zest.examples/build.properties, org.eclipse.zest.sdk-feature/feature.xml
Using https and pointing to the new latest release update site
=> Updates sites referred in features updated

org.eclipse.draw2d-feature/feature.xml, org.eclipse.draw2d.examples/META-INF/MANIFEST.MF, org.eclipse.draw2d.sdk-feature/feature.xml, org.eclipse.gef-feature/feature.xml, org.eclipse.gef.examples-feature/feature.xml, org.eclipse.gef.sdk-feature/feature.xml, org.eclipse.zest-feature/feature.xml, org.eclipse.zest.examples/META-INF/MANIFEST.MF, org.eclipse.zest.sdk-feature/feature.xml
Preparation for the 3.14.0 release work
=> Update of feature id to 3.14.0

org.eclipse.draw2d/META-INF/MANIFEST.MF, org.eclipse.gef/META-INF/MANIFEST.MF, org.eclipse.zest.core/META-INF/MANIFEST.MF
Fixes https://github.com/eclipse/gef-classic/issues/90
=> Remove version from com.ibm.icu.text package import

org.eclipse.gef.examples.flow/src/org/eclipse/gef/examples/flow/parts/SequentialActivityPart.java, org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/LogicFlowEditPolicy.java, org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/LogicResizableEditPolicy.java, org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/LogicTreeContainerEditPolicy.java, org.eclipse.gef.examples.text/src/org/eclipse/gef/examples/text/SelectionRange.java, org.eclipse.gef.examples.text/src/org/eclipse/gef/examples/text/edit/CompoundTextPart.java, org.eclipse.gef/src/org/eclipse/gef/EditPart.java, org.eclipse.gef/src/org/eclipse/gef/SnapToGeometry.java, org.eclipse.gef/src/org/eclipse/gef/editparts/AbstractEditPart.java, org.eclipse.gef/src/org/eclipse/gef/editparts/AbstractGraphicalEditPart.java, org.eclipse.gef/src/org/eclipse/gef/editparts/AbstractTreeEditPart.java, org.eclipse.gef/src/org/eclipse/gef/editpolicies/FlowLayoutEditPolicy.java, org.eclipse.gef/src/org/eclipse/gef/editpolicies/LayoutEditPolicy.java, org.eclipse.gef/src/org/eclipse/gef/editpolicies/ScrollableSelectionFeedbackEditPolicy.java, org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/PaletteStackEditPart.java, org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/PinnablePaletteStackEditPart.java, org.eclipse.gef/src/org/eclipse/gef/internal/ui/rulers/GuideEditPart.java, org.eclipse.gef/src/org/eclipse/gef/ui/actions/SelectAllAction.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/PaletteViewer.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/editparts/PaletteEditPart.java, org.eclipse.gef/src/org/eclipse/gef/ui/parts/GraphicalViewerKeyHandler.java, org.eclipse.gef/src/org/eclipse/gef/ui/parts/PaletteViewerKeyHandler.java, org.eclipse.gef/src/org/eclipse/gef/ui/parts/TreeViewerTransferDropListener.java, org.eclipse.gef/src/org/eclipse/gef/util/EditPartUtilities.java
This reverts commit 85ffd4dbee3542e0af9e5c77c6395cdd2a3a3a40.
=> Revert "[Modernize Code] Turn Editpart children into typed List"

org.eclipse.draw2d/META-INF/MANIFEST.MF, org.eclipse.draw2d/src/org/eclipse/draw2d/text/BidiProcessor.java, org.eclipse.draw2d/src/org/eclipse/draw2d/text/FlowUtilities.java, org.eclipse.gef/META-INF/MANIFEST.MF, org.eclipse.gef/src/org/eclipse/gef/GEF.java, org.eclipse.gef/src/org/eclipse/gef/editparts/ZoomManager.java, org.eclipse.gef/src/org/eclipse/gef/ui/actions/RedoAction.java, org.eclipse.gef/src/org/eclipse/gef/ui/actions/RedoRetargetAction.java, org.eclipse.gef/src/org/eclipse/gef/ui/actions/UndoAction.java, org.eclipse.gef/src/org/eclipse/gef/ui/actions/UndoRetargetAction.java, org.eclipse.gef/src/org/eclipse/gef/ui/properties/SetPropertyValueCommand.java, org.eclipse.zest.core/META-INF/MANIFEST.MF
Remove com.ibm.icu package dependencies
See https://github.com/eclipse/gef-classic/issues/92
=> Remove com.ibm.icu package dependencies

org.eclipse.gef/src/org/eclipse/gef/tools/ResizeTracker.java
This fix adds an additional check that when a resize is performed from
left or top direction that the figure is not moved arround. With that
resize behaves on all directions the same when reaching the min size.
=> Fixes #22: Enforce that on resize the figure is not moved on reaching min size

.mvn/extensions.xml
As Tycho 3.0.0 is used this should be set to the same version
=> Update Tycho extensions file to 3.0.0

org.eclipse.draw2d/META-INF/MANIFEST.MF, org.eclipse.draw2d/src/org/eclipse/draw2d/zoom/AbstractZoomManager.java, org.eclipse.draw2d/src/org/eclipse/draw2d/zoom/ZoomListener.java, org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/LogicLabelEditManager.java, org.eclipse.gef/src/org/eclipse/gef/editparts/ZoomListener.java, org.eclipse.gef/src/org/eclipse/gef/editparts/ZoomManager.java, org.eclipse.gef/src/org/eclipse/gef/internal/ui/rulers/DragGuidePolicy.java, org.eclipse.gef/src/org/eclipse/gef/internal/ui/rulers/GuideEditPart.java, org.eclipse.gef/src/org/eclipse/gef/internal/ui/rulers/RulerFigure.java, org.eclipse.zest.core/src/org/eclipse/zest/core/viewers/ZoomContributionViewItem.java, org.eclipse.zest.core/src/org/eclipse/zest/core/viewers/internal/ZoomManager.java
This is a first attempt to move the ZoomManager and ZoomListener class to draw2d. This includes already a first clean-up of ZoomManager class as well as the usage of the listeners.
It currently does not compile as there is an issue with the access to shared messages.
=> Addresses #100: move ZoomManager to draw 2d

.mvn/extensions.xml, pom.xml
- Contains an important fix
- See https://github.com/eclipse-tycho/tycho/issues/1814
=> Update to Tycho 3.0.1

.mvn/extensions.xml, .mvn/maven.config, pom.xml
@azoitl Please review and commit this before we can fix the unit tests problems. Maven 3.9.0 needs Tycho 3.04.
=> Set Tycho version in maven.config

org.eclipse.draw2d.doc.isv/buildDoc.xml, org.eclipse.gef.doc.isv/buildDoc.xml, org.eclipse.zest.doc.isv/buildDoc.xml
Should fix problem building Javadoc on Windows
=> Use correct path to javadoc.exe on Windows

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/Draw2dTestSuite.java
As these tests are unstable I deactivated them.
=> Deactivated text flow wrap tests

org.eclipse.draw2d/src/org/eclipse/draw2d/ConnectionLayer.java, org.eclipse.draw2d/src/org/eclipse/draw2d/Figure.java
With that the points which are iterating in reverse over all children are clearer marked.
=> Introduce getChildrenRevIterable for Figure

org.eclipse.draw2d/src/org/eclipse/draw2d/Figure.java
@Destrolaric this would be my next one in the chain. I hope it is ok for you.
=> Addresses #155 Typify LayoutListener list

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/PointListTests.java, org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/PointTests.java, org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/Point.java
The new constructor may be used to e.g. create a point, representing the
relative position of the mouse courser, after performing a drag operation.
The new position can then be computed as the sum of the old position
and the move delta.
=> [WB] Add new Constructor to the Point class with a Dimension as argument

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/RectangleTest.java, org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/Rectangle.java
Instead of only being able to shrink a Rectangle symmetrically (meaning top/bottom and left/right), it should also be possible to only shrink one direction at a time.
Methods of the form shrinkX(), have been added, where X stands for the direction that is supposed to be shrunk. Shrinking a rectangle modifies both the x/y coordinate (if necessary) and the width/height.
=> [WB] Add methods to modify the size and location of Rectangles.

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/BaseTestCase.java, org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/IntervalTest.java, org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/Interval.java, org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/Rectangle.java
The Interval is the counterpart to the Rectangle, for 1-dimensional space. Its primary use is to describe the length of rows and columns of layouts, in most cases the GridLayout.
=> [WB] Create a new Interval class to describe distances in 1-d space.

org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/Interval.java
@ptziegler I found two minor things reported by sonar and PDE tools that I fixed in your new interval record.
=> Cleanup of interval record

org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/CGraphNode.java, org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/Graph.java, org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphConnection.java, org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphContainer.java, org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphNode.java, org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/HideNodeHelper.java, org.eclipse.zest.examples/src/org/eclipse/zest/examples/swt/GraphSnippet1.java
Added feature to hide nodes inside a graph.
The feature can be enabled in the Graph-Constructor.
=> Added hide-nodes feature

org.eclipse.draw2d/src/org/eclipse/draw2d/ScalableFreeformLayeredPane.java, org.eclipse.draw2d/src/org/eclipse/draw2d/ScalableLayeredPane.java
=> Fixed zooming when scaled graphics is activated.

org.eclipse.draw2d.examples/src/org/eclipse/draw2d/examples/graph/AbstractGraphDemo.java, org.eclipse.draw2d.examples/src/org/eclipse/draw2d/examples/graph/CompoundGraphDemo.java, org.eclipse.draw2d.examples/src/org/eclipse/draw2d/examples/graph/DirectedGraphDemo.java, org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/LocalOptimizerTest.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/BreakCycles.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/CompoundBreakCycles.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/CompoundHorizontalPlacement.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/CompoundRankSorter.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/CompoundTransposeMetrics.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/ConvertCompoundGraph.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/DirectedGraph.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/Edge.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/GraphUtilities.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/HorizontalPlacement.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/InitialRankSolver.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/LocalOptimizer.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/NestingTree.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/NodeList.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/PopulateRanks.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/Rank.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/RankAssignmentSolver.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/RankSorter.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/SortSubgraphs.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/TightSpanningTreeSolver.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/TransposeMetrics.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/VerticalPlacement.java, org.eclipse.gef.examples.flow/src/org/eclipse/gef/examples/flow/parts/TransitionPart.java
Using typed generics for NodeLists. This allowed quite some code clean-up across the whole draw2d graph package. Similar changes are in work for EdgeList and RankList.
@Destrolaric I would be happy if you could have a look on this PR.
=> [#155] Typed node list

org.eclipse.draw2d.examples/src/org/eclipse/draw2d/examples/graph/CompoundGraphDemo.java, org.eclipse.draw2d.examples/src/org/eclipse/draw2d/examples/graph/DirectedGraphDemo.java, org.eclipse.draw2d/src/org/eclipse/draw2d/FocusTraverseManager.java, org.eclipse.draw2d/src/org/eclipse/draw2d/ShortestPathConnectionRouter.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/BreakCycles.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/CompoundBreakCycles.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/CompoundPopulateRanks.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/CompoundRankSorter.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/ConvertCompoundGraph.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/EdgeList.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/GraphUtilities.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/HorizontalPlacement.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/InitialRankSolver.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/InvertEdges.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/LocalOptimizer.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/Node.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/PopulateRanks.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/RankAssignmentSolver.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/RankSorter.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/RouteEdges.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/TightSpanningTreeSolver.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/TransposeMetrics.java
Using typed generics for EdgeLists. This allowed quite some code clean-up across the whole draw2d graph package. 
@ptziegler @Destrolaric again I would be happy for feedback. 
There is one patch in the stack that would then do something similar for the RankList.
=> [#155] Typed edge list

org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/Graph.java, org.eclipse.zest.examples/src/org/eclipse/zest/examples/swt/GraphSnippet14.java
Created new Zest example for hide-nodes and moved the reveal button from Graph to example
=> Removed reveal button from Graph

org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphConnection.java, org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphItem.java, org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphNode.java
Most of the functionality is already implemented, similar to the isVisible methods so I:
- added a isHighlighted method to the super class GraphItem, with a default implementation as to not create problems downstream
- added @Override notations to already existing methods in GraphNode and GraphConnection
=> isHighlighted method for GraphItems

pom.xml
@ptziegler I think this is what you had in mind or?
=> Use latest GEF Classic target platform for building GEF Classic

org.eclipse.gef.examples.flow/src/org/eclipse/gef/examples/flow/FlowEditorPaletteFactory.java, org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/LogicPlugin.java, org.eclipse.gef.examples.shapes/src/org/eclipse/gef/examples/shapes/ShapesEditor.java, org.eclipse.gef.examples.shapes/src/org/eclipse/gef/examples/shapes/ShapesEditorPaletteFactory.java, org.eclipse.gef/src/org/eclipse/gef/dnd/TemplateTransferDropTargetListener.java
Based on the PR https://github.com/eclipse/gef-classic/pull/275 from @ptziegler all usages of SimpleFactory have been rechecked and if possible the typed version is used.
=> [Modernize Code] Utilize new generic SimpleFactory

org.eclipse.gef.examples.flow/src/org/eclipse/gef/examples/flow/policies/ActivityContainerEditPolicy.java, org.eclipse.gef.examples.flow/src/org/eclipse/gef/examples/flow/policies/ActivitySourceEditPolicy.java, org.eclipse.gef.examples.flow/src/org/eclipse/gef/examples/flow/policies/StructuredActivityLayoutEditPolicy.java, org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/LogicContainerEditPolicy.java, org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/LogicFlowEditPolicy.java, org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/LogicTreeContainerEditPolicy.java, org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/LogicXYLayoutEditPolicy.java, org.eclipse.gef/src/org/eclipse/gef/SnapToGeometry.java, org.eclipse.gef/src/org/eclipse/gef/SnapToGuides.java, org.eclipse.gef/src/org/eclipse/gef/editpolicies/ConstrainedLayoutEditPolicy.java, org.eclipse.gef/src/org/eclipse/gef/editpolicies/OrderedLayoutEditPolicy.java
Based on the PR #275 from @ptziegler  all usages of GroupRequest have been checked and where possible more modern Java code used.
=> [Modernize Code] Use the new typed GroupRequest to clean-up code

org.eclipse.gef.examples.text/src/org/eclipse/gef/examples/text/SelectionModel.java, org.eclipse.gef/META-INF/MANIFEST.MF, org.eclipse.gef/src/org/eclipse/gef/EditPartViewer.java, org.eclipse.gef/src/org/eclipse/gef/dnd/TemplateTransferDragSourceListener.java, org.eclipse.gef/src/org/eclipse/gef/editpolicies/FlowLayoutEditPolicy.java, org.eclipse.gef/src/org/eclipse/gef/print/PrintGraphicalViewerOperation.java, org.eclipse.gef/src/org/eclipse/gef/tools/AbstractTool.java, org.eclipse.gef/src/org/eclipse/gef/tools/SelectEditPartTracker.java, org.eclipse.gef/src/org/eclipse/gef/tools/ToolUtilities.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/CustomizeAction.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/PaletteContextMenuProvider.java, org.eclipse.gef/src/org/eclipse/gef/ui/parts/AbstractEditPartViewer.java, org.eclipse.gef/src/org/eclipse/gef/ui/parts/TreeViewer.java, org.eclipse.gef/src/org/eclipse/gef/ui/parts/TreeViewerTransferDropListener.java
Supports #155.
Tested with:
- GMF Runtime: no changes necessary
- 4diac IDE: has ugly casts that need to be fixed
=> [Modernize Code] typify the selection list of EditPart viewer

org.eclipse.gef/src/org/eclipse/gef/ui/palette/PaletteViewer.java
=> [Modernize Code] Typify platteListeners in PaletteViewer

Jenkinsfile
=> first version of jenkins file with sonar invokation

org.eclipse.draw2d.doc.isv/pom.xml, org.eclipse.draw2d.tests/pom.xml, org.eclipse.gef.doc.isv/pom.xml, org.eclipse.gef.tests/pom.xml, org.eclipse.zest.doc.isv/pom.xml, org.eclipse.zest.tests/pom.xml, pom.xml
Sonar compliant about to maven modules with the same name.
Addresses #290.
=> Changed name of maven root module to org.eclipse.gef.root

org.eclipse.draw2d.doc.isv/pom.xml, org.eclipse.draw2d.tests/pom.xml, org.eclipse.gef.doc.isv/pom.xml, org.eclipse.gef.tests/pom.xml, org.eclipse.zest.doc.isv/pom.xml, org.eclipse.zest.tests/pom.xml, pom.xml
=> Another attempt to name GEF root maven module to make sonar happy

org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/Rectangle.java
Addresses #282.
@ptziegler I think you added that check that I had to rework a bit.
=> Reworked shrink to not create an addtional point

org.eclipse.draw2d/src/org/eclipse/draw2d/DeferredUpdateManager.java, org.eclipse.draw2d/src/org/eclipse/draw2d/Figure.java, org.eclipse.draw2d/src/org/eclipse/draw2d/LightweightSystem.java, org.eclipse.draw2d/src/org/eclipse/draw2d/UpdateManager.java
Upgraded code in Figure, DeferredUpdateMnager, LightweightSystem and UpdateManager.
Addresses #155
=> [Modernize Code] Internal Clean-ups in Figure updating

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/RectangleTest.java, org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/Rectangle.java
Simplify and optimize the intersects checking method of Rectangle.
The following shows the individual steps taken:
```java
int x1 = Math.max(x, rect.x()); // (1)
int x2 = Math.min(x + width, rect.x() + rect.width()); // (2)
int y1 = Math.max(y, rect.y()); // (3)
int y2 = Math.min(y + height, rect.y() + rect.height()); // (4)
return (((x2 - x1) > 0) && ((y2 - y1) > 0)); // (5)
```
```java
return x2 > x1 && y2 > y1; // (6) simplify 5
```
```java
return x1 < x2 && y1 < y2; // (7) reverse operands in 6
```
```java
// (8) insert 1, 2, 3, 4 in 7
return Math.max(x, rect.x()) < Math.min(x + width, rect.x() + rect.width()) 
&& Math.max(y, rect.y()) < Math.min(y + height, rect.y() + rect.height());
```
```java
// (9) factor out min and max w.r.t inequalities in 8
return x < x + width && x < …
```
=> Simplify Rectangle.intersects

org.eclipse.draw2d/META-INF/MANIFEST.MF, org.eclipse.gef/META-INF/MANIFEST.MF, org.eclipse.zest.core/META-INF/MANIFEST.MF, org.eclipse.zest.examples/META-INF/MANIFEST.MF, org.eclipse.zest.layouts/META-INF/MANIFEST.MF
https://github.com/eclipse/gef-classic/issues/309
=> BREE changes require a minor version increment

org.eclipse.draw2d/src/org/eclipse/draw2d/graph/CompoundHorizontalPlacement.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/CompoundRankSorter.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/NestingTree.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/NodeCluster.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/Path.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/ShortestPathRouter.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/SortSubgraphs.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/Vertex.java
The signature of following public methods has been changed:
- ShortestPathRouter.solve(...) Returns a List<? extends Path> instead of raw List
- NodeCluster.adjustRank(...) Expects a collection of NodeCluster indeaf of a raw collection
Resolves ~250 compiler warnings.
#155
=> Typify Draw2D Graph package and resolve raw-type warnings

.gitignore, Jenkinsfile, pom.xml, promotion/pom.xml
https://github.com/eclipse/gef-classic/issues/313
=> Reuse org.eclipse.justj.p2.manager for promotion

setup/GEF.setup, setup/GEFConfiguration.setup
https://github.com/eclipse/gef-classic/issues/308
=> Host the Oomph setups

setup/GEF.setup
https://github.com/eclipse/gef-classic/issues/308
=> Fix GEF.setup logical container reference

CONTRIBUTING.md
https://github.com/eclipse/gef-classic/issues/308
=> Provide a link to the setup configuration

Jenkinsfile
Of course this applies only to the master branch.
https://github.com/eclipse/gef-classic/issues/313
=> Promote build by default

Jenkinsfile
https://github.com/eclipse/gef-classic/issues/313
=> Enable sonar

org.eclipse.draw2d/src/org/eclipse/draw2d/Animation.java, org.eclipse.draw2d/src/org/eclipse/draw2d/FigureUtilities.java, org.eclipse.draw2d/src/org/eclipse/draw2d/GridLayout.java, org.eclipse.draw2d/src/org/eclipse/draw2d/LayeredPane.java, org.eclipse.draw2d/src/org/eclipse/draw2d/ManhattanConnectionRouter.java, org.eclipse.draw2d/src/org/eclipse/draw2d/PolylineConnection.java, org.eclipse.draw2d/src/org/eclipse/draw2d/PrinterGraphics.java, org.eclipse.draw2d/src/org/eclipse/draw2d/SWTGraphics.java, org.eclipse.draw2d/src/org/eclipse/draw2d/ScaledGraphics.java, org.eclipse.draw2d/src/org/eclipse/draw2d/ShortestPathConnectionRouter.java, org.eclipse.draw2d/src/org/eclipse/draw2d/XYLayout.java, org.eclipse.draw2d/src/org/eclipse/draw2d/text/LineRoot.java
=> [Modernize Code] Fixed internal generic usage in draw2d

org.eclipse.gef/src/org/eclipse/gef/KeyHandler.java, org.eclipse.gef/src/org/eclipse/gef/SelectionManager.java, org.eclipse.gef/src/org/eclipse/gef/ThemeConstants.java, org.eclipse.gef/src/org/eclipse/gef/commands/Command.java, org.eclipse.gef/src/org/eclipse/gef/commands/CommandStack.java, org.eclipse.gef/src/org/eclipse/gef/editparts/AbstractConnectionEditPart.java, org.eclipse.gef/src/org/eclipse/gef/editparts/ViewportHelper.java, org.eclipse.gef/src/org/eclipse/gef/editpolicies/BendpointEditPolicy.java, org.eclipse.gef/src/org/eclipse/gef/editpolicies/NonResizableEditPolicy.java, org.eclipse.gef/src/org/eclipse/gef/editpolicies/ResizableEditPolicy.java, org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/DetailedLabelFigure.java, org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/DrawerEditPart.java, org.eclipse.gef/src/org/eclipse/gef/palette/ToolEntry.java, org.eclipse.gef/src/org/eclipse/gef/tools/ToolUtilities.java, org.eclipse.gef/src/org/eclipse/gef/ui/actions/ActionRegistry.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/editparts/PaletteAnimator.java, org.eclipse.gef/src/org/eclipse/gef/ui/parts/PaletteViewerKeyHandler.java
=> [Modernize Code] Use in many places Java generics in GEF plugins

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/LocalOptimizerTest.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/CompoundHorizontalPlacement.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/CompoundRankSorter.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/GraphUtilities.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/HorizontalPlacement.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/InitialRankSolver.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/NodeCluster.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/RankSorter.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/TightSpanningTreeSolver.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/VerticalPlacement.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/VirtualNode.java, org.eclipse.draw2d/src/org/eclipse/draw2d/graph/VirtualNodeCreation.java
=> Reduce deprecated element usage in draw2d graph package

org.eclipse.gef/src/org/eclipse/gef/editpolicies/BendpointEditPolicy.java
=> [Modernize Code] Use typed generics in BendointEditPolicy

org.eclipse.draw2d/src/org/eclipse/draw2d/ViewportAwareConnectionLayerClippingStrategy.java, org.eclipse.draw2d/src/org/eclipse/draw2d/ViewportUtilities.java, org.eclipse.gef/src/org/eclipse/gef/editpolicies/ScrollableSelectionFeedbackEditPolicy.java
=> [Modernize Code] Use typed generics in ViewportUtilities

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/FlowBorderTests.java, org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/TextFlowWrapTest.java, org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/TextualTests.java, org.eclipse.draw2d/src/org/eclipse/draw2d/text/BidiProcessor.java, org.eclipse.draw2d/src/org/eclipse/draw2d/text/FlowBox.java, org.eclipse.draw2d/src/org/eclipse/draw2d/text/FlowContainerLayout.java, org.eclipse.draw2d/src/org/eclipse/draw2d/text/FlowFigure.java, org.eclipse.draw2d/src/org/eclipse/draw2d/text/FlowUtilities.java, org.eclipse.draw2d/src/org/eclipse/draw2d/text/InlineFlow.java, org.eclipse.draw2d/src/org/eclipse/draw2d/text/InlineFlowLayout.java, org.eclipse.draw2d/src/org/eclipse/draw2d/text/LineBox.java, org.eclipse.draw2d/src/org/eclipse/draw2d/text/LineRoot.java, org.eclipse.draw2d/src/org/eclipse/draw2d/text/ParagraphTextLayout.java, org.eclipse.draw2d/src/org/eclipse/draw2d/text/SimpleTextLayout.java, org.eclipse.draw2d/src/org/eclipse/draw2d/text/TextFlow.java, org.eclipse.draw2d/src/org/eclipse/draw2d/text/TextLayout.java
=> [Modernize Code] Use generics in draw2d text

org.eclipse.draw2d/src/org/eclipse/draw2d/ConnectionEndpointLocator.java, org.eclipse.draw2d/src/org/eclipse/draw2d/ConnectionLayer.java, org.eclipse.draw2d/src/org/eclipse/draw2d/ConnectionRouter.java, org.eclipse.draw2d/src/org/eclipse/draw2d/EventListenerList.java, org.eclipse.draw2d/src/org/eclipse/draw2d/FanRouter.java, org.eclipse.draw2d/src/org/eclipse/draw2d/Figure.java, org.eclipse.draw2d/src/org/eclipse/draw2d/FlowLayout.java, org.eclipse.draw2d/src/org/eclipse/draw2d/FocusListener.java, org.eclipse.draw2d/src/org/eclipse/draw2d/FreeformHelper.java, org.eclipse.draw2d/src/org/eclipse/draw2d/Graphics.java, org.eclipse.draw2d/src/org/eclipse/draw2d/LightweightSystem.java, org.eclipse.draw2d/src/org/eclipse/draw2d/OrderedLayout.java, org.eclipse.draw2d/src/org/eclipse/draw2d/PopUpHelper.java, org.eclipse.draw2d/src/org/eclipse/draw2d/SWTGraphics.java, org.eclipse.draw2d/src/org/eclipse/draw2d/ScalablePolygonShape.java, org.eclipse.draw2d/src/org/eclipse/draw2d/TextUtilities.java, org.eclipse.draw2d/src/org/eclipse/draw2d/ToolbarLayout.java, org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/ColumnsLayout.java, org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/PaletteContainerFlowLayout.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/editparts/PaletteToolbarLayout.java
=> Removed usage of deprecated functions in draw2d core package

org.eclipse.draw2d/src/org/eclipse/draw2d/BendpointConnectionRouter.java, org.eclipse.draw2d/src/org/eclipse/draw2d/ShortestPathConnectionRouter.java
=> [Modernize Code] Fixed untyped generics in draw2d connection routers

org.eclipse.draw2d/src/org/eclipse/draw2d/ButtonGroup.java, org.eclipse.draw2d/src/org/eclipse/draw2d/LayoutAnimator.java
=> [Mondernize Code] Typified the last generics in draw2d

org.eclipse.draw2d/src/org/eclipse/draw2d/Figure.java
=> reverted setToolTip to original version to avoid potential recursions

org.eclipse.gef/src/org/eclipse/gef/ui/actions/ActionBarContributor.java, org.eclipse.gef/src/org/eclipse/gef/ui/actions/ActionRegistry.java, org.eclipse.gef/src/org/eclipse/gef/ui/actions/AlignmentAction.java, org.eclipse.gef/src/org/eclipse/gef/ui/actions/Clipboard.java, org.eclipse.gef/src/org/eclipse/gef/ui/actions/CopyTemplateAction.java, org.eclipse.gef/src/org/eclipse/gef/ui/actions/DeleteAction.java, org.eclipse.gef/src/org/eclipse/gef/ui/actions/DirectEditAction.java, org.eclipse.gef/src/org/eclipse/gef/ui/actions/MatchSizeAction.java, org.eclipse.gef/src/org/eclipse/gef/ui/actions/PasteTemplateAction.java, org.eclipse.gef/src/org/eclipse/gef/ui/actions/RedoAction.java, org.eclipse.gef/src/org/eclipse/gef/ui/actions/RedoRetargetAction.java, org.eclipse.gef/src/org/eclipse/gef/ui/actions/StackAction.java, org.eclipse.gef/src/org/eclipse/gef/ui/actions/UndoAction.java, org.eclipse.gef/src/org/eclipse/gef/ui/actions/UndoRetargetAction.java, org.eclipse.gef/src/org/eclipse/gef/ui/actions/ZoomComboContributionItem.java
=> [Modernize Code] Clean generic usage in gef actions

org.eclipse.gef.examples.flow/src/org/eclipse/gef/examples/flow/FlowEditorPaletteFactory.java, org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/LogicPlugin.java, org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/ToolbarDropdownContributionItem.java, org.eclipse.gef/src/org/eclipse/gef/palette/PaletteContainer.java, org.eclipse.gef/src/org/eclipse/gef/palette/PaletteDrawer.java, org.eclipse.gef/src/org/eclipse/gef/palette/PaletteEntry.java, org.eclipse.gef/src/org/eclipse/gef/palette/PaletteGroup.java, org.eclipse.gef/src/org/eclipse/gef/palette/PaletteStack.java, org.eclipse.gef/src/org/eclipse/gef/palette/PaletteToolbar.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/FlyoutPaletteComposite.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/LayoutAction.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/PaletteContextMenuProvider.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/PaletteCustomizer.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/PaletteEditPartFactory.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/PaletteViewerProvider.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/customize/DefaultEntryPage.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/customize/DrawerEntryPage.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/customize/PaletteContainerFactory.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/customize/PaletteCustomizerDialog.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/customize/PaletteEntryFactory.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/customize/PaletteLabelProvider.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/customize/PaletteSeparatorFactory.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/customize/PaletteSettingsDialog.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/customize/PaletteTreeProvider.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/editparts/PaletteEditPart.java
=> [Modernize Code ] Clean-up generics and surrounding code in GEF Palette

org.eclipse.draw2d/src/org/eclipse/draw2d/FigureCanvas.java
FigureCanvas' scrollToX and scrollToY uses an optimized scrolling functionality which leads especially for views with many figures to a much smoother scrolling experience. This commit utilizes this optimized scrolling also for scrollTo. Furthermore the code for all three has been combined in such a way that all three use the same core functions.
This work is triggered by the analysis of @BauePhil noticing that the `scrollTo()` resulted in a worse user experience in larger Zest graphs compared to the two `scrollToX()` and `scrollToY()` functions.  Today I finally found the reason for this. `scrollTo()` triggers **twice** (x and y) the range model resulting in triggering the propertyChange method of the Viewport, which invalidated the figure.  Already for mid-sized figures the change …
=> Use optimized scrolling for all three scroll operations of FigureCanvas

org.eclipse.gef/src/org/eclipse/gef/GraphicalEditPart.java, org.eclipse.gef/src/org/eclipse/gef/editparts/AbstractGraphicalEditPart.java, org.eclipse.gef/src/org/eclipse/gef/editpolicies/ScrollableSelectionFeedbackEditPolicy.java, org.eclipse.gef/src/org/eclipse/gef/ui/parts/GraphicalViewerKeyHandler.java, org.eclipse.gef/src/org/eclipse/gef/util/EditPartUtilities.java
=> [Modernize Code] Typefy getSourceConnections and getTargetConnections of GraphicalEditPart

org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/GateEditPart.java, org.eclipse.gef/src/org/eclipse/gef/AccessibleAnchorProvider.java, org.eclipse.gef/src/org/eclipse/gef/AccessibleHandleProvider.java, org.eclipse.gef/src/org/eclipse/gef/editparts/AbstractConnectionEditPart.java, org.eclipse.gef/src/org/eclipse/gef/editparts/AbstractGraphicalEditPart.java, org.eclipse.gef/src/org/eclipse/gef/tools/ConnectionCreationTool.java, org.eclipse.gef/src/org/eclipse/gef/tools/ConnectionEndpointTracker.java, org.eclipse.gef/src/org/eclipse/gef/tools/SelectionTool.java
=> [Modernize Code] Typify lists of AccessibleXXProviders

org.eclipse.gef.examples.digraph1/src/org/eclipse/gef/examples/digraph1/editor/Digraph1GraphicalEditor.java, org.eclipse.gef/src/org/eclipse/gef/internal/ui/rulers/RulerDragTracker.java, org.eclipse.gef/src/org/eclipse/gef/tools/AbstractConnectionCreationTool.java, org.eclipse.gef/src/org/eclipse/gef/tools/AbstractTool.java, org.eclipse.gef/src/org/eclipse/gef/tools/ConnectionBendpointTracker.java, org.eclipse.gef/src/org/eclipse/gef/tools/ConnectionCreationTool.java, org.eclipse.gef/src/org/eclipse/gef/tools/ConnectionEndpointTracker.java, org.eclipse.gef/src/org/eclipse/gef/tools/CreationTool.java, org.eclipse.gef/src/org/eclipse/gef/tools/DragEditPartsTracker.java, org.eclipse.gef/src/org/eclipse/gef/tools/DragTreeItemsTracker.java, org.eclipse.gef/src/org/eclipse/gef/tools/MarqueeDragTracker.java, org.eclipse.gef/src/org/eclipse/gef/tools/PanningSelectionTool.java, org.eclipse.gef/src/org/eclipse/gef/tools/ResizeTracker.java, org.eclipse.gef/src/org/eclipse/gef/tools/SimpleDragTracker.java, org.eclipse.gef/src/org/eclipse/gef/tools/TargetingTool.java, org.eclipse.gef/src/org/eclipse/gef/tools/ToolUtilities.java
=> [Modernize Code] Cleaned all GEF Tools

org.eclipse.gef/src/org/eclipse/gef/tools/DirectEditManager.java
=> [Modernize Code] Typify Class in DirectEditManager

CHANGELOG.md, org.eclipse.draw2d/src/org/eclipse/draw2d/AbstractConstraintLayout.java, org.eclipse.draw2d/src/org/eclipse/draw2d/DelegatingLayout.java, org.eclipse.draw2d/src/org/eclipse/draw2d/XYLayout.java, org.eclipse.gef/src/org/eclipse/gef/internal/ui/rulers/RulerLayout.java
XYLayout and RulerLayout share quite some common code. This is extracted in a common base class to be used also by other Layouts.
=> Extract Constraint handling into AbstractConstraintLayout

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/XYLayoutTest.java, org.eclipse.draw2d/src/org/eclipse/draw2d/GridLayout.java, org.eclipse.draw2d/src/org/eclipse/draw2d/XYLayout.java, org.eclipse.draw2d/src/org/eclipse/draw2d/internal/Messages.java, org.eclipse.draw2d/src/org/eclipse/draw2d/internal/Messages.properties, org.eclipse.gef.tests/src/org/eclipse/gef/test/RulerLayoutTests.java, org.eclipse.gef/src/org/eclipse/gef/internal/ui/rulers/RulerLayout.java
=> XYLayout and RulerLayout shouldn't throw exception on invalid constraint

org.eclipse.zest.examples/src/org/eclipse/zest/examples/jface/GraphJFaceSnippet7.java, org.eclipse.zest.examples/src/org/eclipse/zest/examples/swt/GraphSnippet2.java, org.eclipse.zest.examples/src/org/eclipse/zest/examples/swt/GraphSnippet3.java, org.eclipse.zest.examples/src/org/eclipse/zest/examples/swt/GraphSnippet4.java, org.eclipse.zest.examples/src/org/eclipse/zest/examples/swt/GraphSnippet5.java, org.eclipse.zest.examples/src/org/eclipse/zest/examples/swt/GraphSnippet6.java
Some of the images are not properly disposed after the examples is closed, while other dispose system images.
=> Cleanup disposed images in Zest examples

org.eclipse.gef.tests/META-INF/MANIFEST.MF, org.eclipse.gef.tests/pom.xml, org.eclipse.gef.tests/src/org/eclipse/gef/test/GraphicalViewerTest.java, org.eclipse.gef.tests/src/org/eclipse/gef/test/swtbot/AbstractSWTBotTests.java, org.eclipse.gef.tests/src/org/eclipse/gef/test/swtbot/FlowDiagramTests.java, org.eclipse.gef.tests/src/org/eclipse/gef/test/swtbot/LogicDiagramTests.java, org.eclipse.gef.tests/src/org/eclipse/gef/test/swtbot/SWTBotTestSuite.java, org.eclipse.gef.tests/src/org/eclipse/gef/test/swtbot/ShapesDiagramTests.java, setup/GEF.setup, target-platform/GEF_classic.target
I dabbled a little into SWTBot and in general, this should all work out.
To note:
- The tests must not be executed in the UI thread.
- The record feature of SWTBot produces invalid Java code.
I'm not very creative when it comes to use cases, so right now I'm only testing basic features like add/removing items and/or connections. Or the Undo/Redo functionality.
=> Create integration tests using GEF examples and SWTBot.

org.eclipse.gef/src/org/eclipse/gef/internal/ui/rulers/DragGuidePolicy.java, org.eclipse.gef/src/org/eclipse/gef/internal/ui/rulers/GuideEditPart.java, org.eclipse.gef/src/org/eclipse/gef/internal/ui/rulers/GuideFigure.java, org.eclipse.gef/src/org/eclipse/gef/internal/ui/rulers/RulerContextMenuProvider.java, org.eclipse.gef/src/org/eclipse/gef/internal/ui/rulers/RulerEditPartFactory.java, org.eclipse.gef/src/org/eclipse/gef/rulers/RulerChangeListener.java, org.eclipse.gef/src/org/eclipse/gef/rulers/RulerProvider.java
Added types to generics and fixed issues reported by Java compiler and SonarLint.
https://github.com/eclipse/gef-classic/issues/155
=> Cleaned Ruler classes #155

org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/TreeLayoutObserver.java
Primarily warnings related to raw types and and potentially static methods.
=> [Zest 2.0] Cleanup compiler warnings in TreeLayoutObserver

org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/SpringLayoutAlgorithm.java
Removes unused variables, handles potentially static methods and resolves the usage of raw types.
=> [Zest 2.0] Cleanup compiler warnings in SpringLayoutAlgorithm

org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/LayoutAlgorithm.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/LayoutEntity.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/LayoutGraph.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/LayoutRelationship.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/AbstractLayoutAlgorithm.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/ContinuousLayoutAlgorithm.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/SpringLayoutAlgorithm.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/SugiyamaLayoutAlgorithm.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/TreeLayoutAlgorithm.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/TreeLayoutObserver.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/dataStructures/DisplayIndependentPoint.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/interfaces/ContextListener.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/interfaces/ExpandCollapseManager.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/interfaces/GraphStructureListener.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/interfaces/LayoutContext.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/interfaces/LayoutListener.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/interfaces/PruningListener.java
Invalid method signatures, undocumented return types etc.
=> [Zest 2.0] Resolve JavaDoc warnings

org.eclipse.zest.cloudio/src/org/eclipse/zest/cloudio/Activator.java, org.eclipse.zest.cloudio/src/org/eclipse/zest/cloudio/CloudOptionsComposite.java, org.eclipse.zest.cloudio/src/org/eclipse/zest/cloudio/Messages.java, org.eclipse.zest.cloudio/src/org/eclipse/zest/cloudio/TagCloud.java, org.eclipse.zest.cloudio/src/org/eclipse/zest/cloudio/TagCloudViewer.java, org.eclipse.zest.cloudio/src/org/eclipse/zest/cloudio/Word.java, org.eclipse.zest.cloudio/src/org/eclipse/zest/cloudio/layout/DefaultLayouter.java, org.eclipse.zest.cloudio/src/org/eclipse/zest/cloudio/messages.properties, org.eclipse.zest.cloudio/src/org/eclipse/zest/cloudio/util/SmallRect.java
Error messages remaining untranslated, everything else that is shown in the UI (dialogs/widgets) have been exported to a messages.properties file.
=> [Zest 2.0] Resolve i18n warnings in CloudIO component

org.eclipse.zest.examples.layouts/src/org/eclipse/zest/layouts/exampleUses/SimpleSWTExample.java, org.eclipse.zest.examples/src/org/eclipse/zest/examples/swt/CustomLayout.java, org.eclipse.zest.layouts/.settings/.api_filters, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/AbstractLayoutAlgorithm.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/CompositeLayoutAlgorithm.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/ContinuousLayoutAlgorithm.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/DirectedGraphLayoutAlgorithm.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/GridLayoutAlgorithm.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/HorizontalShift.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/HorizontalShiftAlgorithm.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/RadialLayoutAlgorithm.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/SpaceTreeLayoutAlgorithm.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/SpringLayoutAlgorithm.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/SugiyamaLayoutAlgorithm.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/TreeLayoutAlgorithm.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/internal/CycleChecker.java, org.eclipse.zest.tests/src/org/eclipse/zest/tests/examples/AbstractGraphTest.java
Clients should not implement the LayoutAlgorithm interface directly as we may want to add new methods in the future (similar to the Zest 1.0 case). Instead, they should implement the AbstractLayoutAlgorithm class.
=> [Zest 2.0] Create abstract base class for new Zest layout algorithms.

CHANGELOG.md
I don't think it's worth mentioning every bugfix. @azoitl Do you see anything I've missed?
=> Update changelog for 3.21 release

org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/dataStructures/DisplayIndependentDimension.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/dataStructures/DisplayIndependentPoint.java, org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/dataStructures/DisplayIndependentRectangle.java
The %d is for integer values so it simply doesn't work.
=> Format double with %f not %d

org.eclipse.draw2d.examples/src/org/eclipse/draw2d/examples/tree/TreeLayout.java, org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/LogicLabelEditPart.java, org.eclipse.gef.examples.shapes/src/org/eclipse/gef/examples/shapes/parts/ConnectionEditPart.java, org.eclipse.gef.examples.shapes/src/org/eclipse/gef/examples/shapes/parts/DiagramEditPart.java, org.eclipse.gef.examples.shapes/src/org/eclipse/gef/examples/shapes/parts/DiagramTreeEditPart.java, org.eclipse.gef.examples.shapes/src/org/eclipse/gef/examples/shapes/parts/ShapeEditPart.java, org.eclipse.gef.examples.text/src/org/eclipse/gef/examples/text/edit/DocumentPart.java, org.eclipse.gef/src/org/eclipse/gef/editparts/AbstractGraphicalEditPart.java, org.eclipse.gef/src/org/eclipse/gef/ui/palette/customize/PaletteCustomizerDialog.java
With the improved typing in several places casts could be removed. Making code better readable and cleaner.
Addresses: https://github.com/eclipse/gef-classic/issues/155
=> Removed Unnecessary Casts #155

org.eclipse.gef/src/org/eclipse/gef/ui/parts/AbstractEditPartViewer.java
Addresses: https://github.com/eclipse/gef-classic/issues/155
=> Added types to AbstractEditPartViewer's Selection #155

org.eclipse.gef/src/org/eclipse/gef/ui/parts/TreeViewerTransfer.java, org.eclipse.gef/src/org/eclipse/gef/ui/parts/TreeViewerTransferDragListener.java, org.eclipse.gef/src/org/eclipse/gef/ui/parts/TreeViewerTransferDropListener.java
As we now have more typed lists the handling of selections and the resulting DnD actions can be implemented more nicely.
Addresses: https://github.com/eclipse/gef-classic/issues/155
=> Used Typed new Generics for selection in TreeViewer DnD Classes #155

org.eclipse.gef/src/org/eclipse/gef/editparts/AbstractGraphicalEditPart.java
https://github.com/eclipse-gef/gef-classic/issues/155
=> Added Generic Paramters for getModelSource and TargetConnectins #155

org.eclipse.zest.examples/src/org/eclipse/zest/examples/jface/GraphJFaceSnippet1.java, org.eclipse.zest.examples/src/org/eclipse/zest/examples/jface/GraphJFaceSnippet2.java, org.eclipse.zest.examples/src/org/eclipse/zest/examples/jface/GraphJFaceSnippet3.java, org.eclipse.zest.examples/src/org/eclipse/zest/examples/jface/GraphJFaceSnippet4.java, org.eclipse.zest.examples/src/org/eclipse/zest/examples/jface/GraphJFaceSnippet5.java, org.eclipse.zest.examples/src/org/eclipse/zest/examples/jface/GraphJFaceSnippet6.java, org.eclipse.zest.examples/src/org/eclipse/zest/examples/jface/GraphJFaceSnippet7.java, org.eclipse.zest.examples/src/org/eclipse/zest/examples/jface/GraphJFaceSnippet8.java, org.eclipse.zest.examples/src/org/eclipse/zest/examples/jface/ManhattanLayoutJFaceSnippet.java
Applies the default format on the classes and removes obsolete/unused methods.
=> Cleanup and re-format Zest JFace snippets

org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/GroundFeedbackFigure.java, org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/GroundFigure.java, org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/LiveOutputFeedbackFigure.java, org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/LiveOutputFigure.java, org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/OutputFigure.java
Changes:
Increased size of ground and output figures to double their original size
Maintained original aspect ratios and proportions
=> Double size of ground and output figures

org.eclipse.zest.cloudio/src/org/eclipse/zest/cloudio/TagCloud.java
Doing UI stuff outside the UI thread is generally a bad idea. The initial motivation seems to have been due to performance reason. But at least GTK synchronizes access to the UI thread. So even if multiple threads paint at the same time, the operation is still performed sequentially.
Closes https://github.com/eclipse-gef/gef-classic/issues/697
=> Move paint operation in Cloud viewer back to UI thread

org.eclipse.gef/META-INF/MANIFEST.MF
https://github.com/eclipse-gef/gef-classic/pull/734
=> Raise minor version in GEF after changes to FlyoutPaletteComposite

org.eclipse.draw2d/src/org/eclipse/draw2d/parts/ScrollableThumbnail.java
=> Fix ScrollableThumbnail offset calculation

org.eclipse.gef.examples.text/META-INF/MANIFEST.MF, org.eclipse.gef.examples.text/src/org/eclipse/gef/examples/text/wizard/NewFileWizardPage.java, org.eclipse.gef.examples.text/src/org/eclipse/gef/examples/text/wizard/TextEditorWizard.java
The Eclipse IDE already provides a perfectly fine wizard page for creating new files. There is no need to re-implement existing functionality.
=> Use WizardNewFileCreationPage for "New Document Example" wizard page
