org.eclipse.gef.repository/category.xml
pom.xml

This commits adds the following to the update:
gef-sdk feature
zest.examples plugin
draw2d.examples plugin
Fixes #9

Adding missing plug-ins and GEF SDK feature to update site

---

CONTRIBUTING.md

As requested by the project release review, we should update the link to the new ELA link and use the correct termilogy.

Update the contribution file with new ELA link

---

org.eclipse.draw2d.examples/META-INF/MANIFEST.MF
org.eclipse.gef.examples-feature/feature.xml
org.eclipse.gef.repository/category.xml
org.eclipse.zest.examples/META-INF/MANIFEST.MF
org.eclipse.zest.examples/build.properties

Examples versions are aligned with feature and release number
gef-example feature number has been changed to 3.13
Missing build.properties entry added

More version alignments for the 3.13.0 release

---

org.eclipse.draw2d-feature/feature.xml
org.eclipse.draw2d.sdk-feature/feature.xml
org.eclipse.gef-feature/feature.xml
org.eclipse.gef.repository/category.xml
org.eclipse.gef.sdk-feature/feature.xml
org.eclipse.zest-feature/feature.xml
org.eclipse.zest.sdk-feature/feature.xml

Also add the org.eclipse.draw2d.sdk to the category.xml
https://github.com/eclipse/gef-classic/issues/70

Keep  keep original feature IDs intact

---

org.eclipse.gef.baseline/API-baseline-3.14.0/gef-classic-3.14.0.target

Added a target platform with the 3.14 release for use as api base line in pde tools.

Add api baseline target for 3.14.0 release

---

org.eclipse.gef.examples.flow/src/org/eclipse/gef/examples/flow/parts/SequentialActivityPart.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/LogicFlowEditPolicy.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/LogicResizableEditPolicy.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/LogicTreeContainerEditPolicy.java
org.eclipse.gef.examples.text/src/org/eclipse/gef/examples/text/SelectionRange.java
org.eclipse.gef.examples.text/src/org/eclipse/gef/examples/text/edit/CompoundTextPart.java
org.eclipse.gef/src/org/eclipse/gef/EditPart.java
org.eclipse.gef/src/org/eclipse/gef/SnapToGeometry.java
org.eclipse.gef/src/org/eclipse/gef/editparts/AbstractEditPart.java
org.eclipse.gef/src/org/eclipse/gef/editparts/AbstractGraphicalEditPart.java
org.eclipse.gef/src/org/eclipse/gef/editparts/AbstractTreeEditPart.java
org.eclipse.gef/src/org/eclipse/gef/editpolicies/FlowLayoutEditPolicy.java
org.eclipse.gef/src/org/eclipse/gef/editpolicies/LayoutEditPolicy.java
org.eclipse.gef/src/org/eclipse/gef/editpolicies/ScrollableSelectionFeedbackEditPolicy.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/PaletteStackEditPart.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/PinnablePaletteStackEditPart.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/rulers/GuideEditPart.java
org.eclipse.gef/src/org/eclipse/gef/ui/actions/SelectAllAction.java
org.eclipse.gef/src/org/eclipse/gef/ui/palette/PaletteViewer.java
org.eclipse.gef/src/org/eclipse/gef/ui/palette/editparts/PaletteEditPart.java
org.eclipse.gef/src/org/eclipse/gef/ui/parts/GraphicalViewerKeyHandler.java
org.eclipse.gef/src/org/eclipse/gef/ui/parts/PaletteViewerKeyHandler.java
org.eclipse.gef/src/org/eclipse/gef/ui/parts/TreeViewerTransferDropListener.java
org.eclipse.gef/src/org/eclipse/gef/util/EditPartUtilities.java

One of the biggest drawbacks of current GEF Classic code is that it is not yet using typed generics. This requires a lot of checks and casts in client code. This commit is a start to move GEF Classic to a more modern java.

[Modernize Code] Turn Editpart children into typed List

---

org.eclipse.draw2d/src/org/eclipse/draw2d/parts/Thumbnail.java

Draft PR for discussion in order to workaround #4.
There is overhead in allocating new instances of GC, SWTGraphics, and ScaledGraphics, and there may be a better workaround, but this one is certainly tried and tested and at least shows the problem.
Refactor so that new instances of `GC`, `SWTGraphics`, and `ScaledGraphics` are created in the `createTileGraphics()` method that can be called in the `run()` method if on Mac

Fix thumbnail not working on Mac

---

org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/Graph.java

As the Viewport already redraws the Graph on demand redrawing upon moving the scrollbars is unnecessary and reduces performance in bigger graphs.

removed unnecessary redrawing of zest Graph upon scrolling

---

org.eclipse.draw2d/src/org/eclipse/draw2d/SWTGraphics.java

- Under some circumstances currentState.relativeClip can be null and will throw a NPE
- This checks for a null value

Check for possible null value to avoid NPE

---

org.eclipse.zest.core/META-INF/MANIFEST.MF
org.eclipse.zest.core/src/org/eclipse/zest/core/viewers/internal/AbstractStructuredGraphViewer.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphConnection.java

Seems like the original Idea was to make the graph nodes and connections extendable (i.e. [CGraphNode](https://github.com/eclipse/gef-classic/blob/master/org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/CGraphNode.java)) and just have not been implemented in a way to accomplish this. I added exposed create methods and added the original object creation in the overridden methods in the GraphViewer.

enable custom graph nodes and connections

---

Jenkinsfile
pom.xml
target-platform/2022-09.target

@vogella as we got the Jenkins problem I did the long due upgrade to the latest Eclipse platform. As part of that I would have a best practice question. Does it make sense to have an individual target file per Eclipse release or is it simpler to just have a gef target plaform file that we regularly update?

Updated target platform to 2022-09 and to Tycho 3.0.0

---

org.eclipse.draw2d/META-INF/MANIFEST.MF
org.eclipse.draw2d/src/org/eclipse/draw2d/text/BidiProcessor.java
org.eclipse.draw2d/src/org/eclipse/draw2d/text/FlowUtilities.java

- Use com.ibm.icu.text classes for Bidi and BreakIterator
- This will restore original BreakIterator's line break behaviour and possible changes in Bidi behaviour
- See #116

Partially revert removal of com.ibm.icu package dependencies

---

org.eclipse.gef/src/org/eclipse/gef/tools/SelectionTool.java
org.eclipse.gef/src/org/eclipse/gef/ui/parts/GraphicalViewerKeyHandler.java

- The isEnqueued() check is not needed because get() will return null if this reference object has been cleared
- See https://github.com/eclipse/gef-classic/issues/122

Remove redundant isEnqueued() checks

---

org.eclipse.draw2d/src/org/eclipse/draw2d/NativeGraphicsSource.java

Don't call canvas.update() in NativeGraphicsSource#getGraphics
This is needed to avoid SWT/GEF bug 137786 where drag over feedback (ie the drag feedback provided by the drag source) and drag under feedback (ie the feedback provided by the drop target) interfere with each other, causing flickering and more importantly ugly graphical artifacts.
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=137786

Fix drag operation unwanted artifacts

---

org.eclipse.draw2d/src/org/eclipse/draw2d/zoom/AbstractZoomManager.java
org.eclipse.draw2d/src/org/eclipse/draw2d/zoom/DefaultScrollPolicy.java
org.eclipse.draw2d/src/org/eclipse/draw2d/zoom/IZoomScrollPolicy.java
org.eclipse.draw2d/src/org/eclipse/draw2d/zoom/MouseLocationZoomScrollPolicy.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/LogicEditor.java
org.eclipse.gef/src/org/eclipse/gef/editparts/ZoomManager.java

With a zoom scroll policy a client can adjust how the scroll position should be maintained during zooming. Two implementations are provided:
- The default which is the original GEF Classic behavior (i.e. maintain the center of the diagram)
- The mouse location based which tries to maintain the location under the mouse
This is a first POC for getting feedback. More documentation is needed.

Addresses #124: A first proposal for IZoomScrollPolicies

---

CHANGELOG.md
org.eclipse.draw2d.doc.isv/pom.xml
org.eclipse.draw2d.doc.isv/topics_Reference.xml
org.eclipse.draw2d/src/org/eclipse/draw2d/zoom/package.html

- updated CHANGELOG.md
- added new org.eclipse.draw2d.zoom  package to Draw2d documentation
- enabled documentation generation in draw2d doc project

Updated Documenation for 3.15 release

---

org.eclipse.draw2d/.settings/.api_filters
org.eclipse.draw2d/META-INF/MANIFEST.MF
org.eclipse.draw2d/build.properties
org.eclipse.draw2d/css/gef_dark.css
org.eclipse.draw2d/plugin.properties
org.eclipse.draw2d/plugin.xml
org.eclipse.draw2d/src/org/eclipse/draw2d/ColorConstants.java
org.eclipse.draw2d/src/org/eclipse/draw2d/ColorProvider.java
org.eclipse.draw2d/src/org/eclipse/draw2d/ColorProviderDefault.java
org.eclipse.draw2d/src/org/eclipse/draw2d/ThemeConstants.java
org.eclipse.draw2d/src/org/eclipse/draw2d/zoom/AbstractZoomManager.java
org.eclipse.draw2d/src/org/eclipse/draw2d/zoom/DefaultScrollPolicy.java
org.eclipse.draw2d/src/org/eclipse/draw2d/zoom/IZoomScrollPolicy.java
org.eclipse.draw2d/src/org/eclipse/draw2d/zoom/MouseLocationZoomScrollPolicy.java
org.eclipse.draw2d/src/org/eclipse/draw2d/zoom/ZoomListener.java
org.eclipse.gef/src/org/eclipse/gef/editparts/GridLayer.java
org.eclipse.gef/src/org/eclipse/gef/internal/InternalImages.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/PaletteColorUtil.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/DrawerFigure.java
org.eclipse.gef/src/org/eclipse/gef/ui/palette/customize/PaletteLabelProvider.java

Pr adds an ability to customize colors via `org.eclipse.ui.themes`. Colors could be configured via preferences or theme settings. Additionally adds an ability to override configured images to support more extensive customization. This improvement will allow for the palette and other components to be configured for a black theme.

Adresses #128 add color customization and icon overloads

---

.github/workflows/maven.yml

Currently we use Java 11 and Java 17, if GEF moves to Java 17 we may want to use latest and greatest in addition to Java 17.

GH verification build on Linux and Windows and multiple Java versions

---

.github/workflows/maven.yml
.github/workflows/unit-tests.yml
pom.xml

With this change, test failures are no longer silently ignored. When a failure has been detected, all remaining test cases continue to be executed, then the Maven build throws an error.
Regardless of the successful build, the test results for each job are uploaded to GitHub.
Once the job has completed, a new workflow action is executed, which aggregates all test results and publishes them within the GitHub action.

Add a new job to the GitHub action for publishing the test results.

---

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/ConnectionEndPointMoveTest.java
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/Draw2dTestSuite.java
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/LookAheadTest.java
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/PaintDamageEraseTest.java

ConnectionEndPointMove test did correctly wait for all updates to be dispatched. This resulted in different test results depending if executed alone or as part of Draw2d's test suite. This is fixed now.

Stabilized Draw2d Tests

---

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/BaseTestCase.java
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/TransposerTest.java
org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/Transposer.java

Instead of:
Transposer t = new Transposer();
t.setEnabled(true);
One can simply do this:
Transposer t = new Transposer(true);

[WB] Add constructor to set the "enabled" flag when creating Transposers

---

org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/Translatable.java

Extend the interface to also allow calling the performTranslate method for points, dimensions and insets. For the sake of backwards-compatibility, provide a default implementation.

[WB] Extend Translatable interface with additional default methods.

---

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/PaintDamageEraseTest.java

It appears as if pumping the SWT event queue only once is not sufficient to process the update of the UpdateManager instance.
Define a new method which pumps the SWT events for an arbitrary but fixed amount of time.

[JUnit] Stabilize PaintDamageEraseTest and split up test cases

---

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/BaseTestCase.java
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/ConnectionEndPointMoveTest.java
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/PaintDamageEraseTest.java

Use the same approach used to stabilize the PaintDamageErase tests. When pumping the SWT event loop only once, the update of the UpdateManager may have not been fully performed. In order to ensure that it has been fully processed, pump the events for an arbitrary but fixed amount of time.
For the sake of reusability, the waitEventLoop method has been moved to the BaseTestCase class. Both test cases extend this base class in order to access this method. The ConnectionEndPointMove test will pump SWT events for a total of 100ms.

[JUnit] Stabilize ConnectionEndPointMoveTest via waitEventLoop method

---

org.eclipse.draw2d/.settings/org.eclipse.jdt.core.prefs

The properties 'org.eclipse.jdt.core.compiler.codegen.targetPlatform' and 'org.eclipse.jdt.core.compiler.source' are still set to Java 11. As a result, language features such as records are not recognized within the IDE.
See #146

Update compiler compliance of org.eclipse.draw2d to Java 17

---

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/AdvancedGraphicsTests.java
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/BaseTestCase.java
pom.xml

It seems like the way timed jobs are executed on MacOS slightly differs from Windows and Linux. As a result, it might happen that a job is scheduled but the UI thread is never woken up again. As a result, the test case is stuck indefinitely, until it is aborted by GitHub.
To avoid this problem, add this job asynchronously. This way, the job is immediately added to the event queue. Furthermore, don't call sleep() while pumping the event queue, in order to avoid missing out on wake-up events.
To avoid issues like this in the future, specify a 5min timeout for each test bundle. Given that we share our build nodes with the other Eclipse projects, a job being stuck for 6h means that other developers might not be able to run their builds for this amount of time. So we should fail early, to free …

[JUnit] Stabilize tests on MacOS and define 5min timeout

---

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/RectangleTest.java
org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/Rectangle.java

This negative value occurs when the rectangle has a border, but its height or width is smaller than the height or width of its insets. The shrink method then tries to reduce the width/height of the rectangle by the width/height of the Insets which may then load to an error.

Adjust shrink method of rectangles to prevent negative width/height.

---

org.eclipse.draw2d/src/org/eclipse/draw2d/ExclusionSearch.java
org.eclipse.draw2d/src/org/eclipse/draw2d/Figure.java
org.eclipse.draw2d/src/org/eclipse/draw2d/IFigure.java
org.eclipse.gef.examples.shapes/src/org/eclipse/gef/examples/shapes/ShapesEditor.java
org.eclipse.gef/src/org/eclipse/gef/EditPartViewer.java
org.eclipse.gef/src/org/eclipse/gef/dnd/AbstractTransferDropTargetListener.java
org.eclipse.gef/src/org/eclipse/gef/tools/ConnectionEndpointTracker.java
org.eclipse.gef/src/org/eclipse/gef/tools/DragEditPartsTracker.java
org.eclipse.gef/src/org/eclipse/gef/tools/TargetingTool.java
org.eclipse.gef/src/org/eclipse/gef/ui/parts/AbstractEditPartViewer.java
org.eclipse.gef/src/org/eclipse/gef/ui/parts/GraphicalViewerImpl.java
org.eclipse.gef/src/org/eclipse/gef/ui/parts/TreeViewerTransferDropListener.java
org.eclipse.gef/src/org/eclipse/gef/ui/rulers/RulerComposite.java

With this cleanup the figure and edipart search was typified. As part of
this work it was identified that the TargetingTool documentation was
wrong. While there it was written that getExclusion set provides
editparts all its children provided a list of IFigures. Also the search
expected IFigures.
Furthermore AbstractTransferDropTargetListener delivered EditParts but
the search required IFigures. The code was fixed here was well and by
typifying the Collections it is now clearer.
@Destrolaric this would be my last commit for Issue #155 for now.

Addresses #155: Typifysearch

---

org.eclipse.gef/META-INF/MANIFEST.MF

GEF 3.14 requires as minimum version draw2d 3.13.0. This is now fixed in GEF manifest.

Fix GEF plugin project setup

---

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/PointListTests.java
org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/PointList.java

The getBounds() method is supposed to return the minimal rectangle enclosing all points. When a point inside this PointList is updated via setPoint() and the point is contained in the current bounds, then the current rectangle has to be invalidated, s.t. getBounds() has to calculate a new, potentially smaller rectangle.
Resolves #219

PointList bounds not updated when using setPoint()

---

.github/workflows/maven.yml
.mvn/maven.config

The latest Tycho release added several performance improvements related to slow proxy repositories. This should reduce the amount of time it takes to resolve the target platform.
Note that this also updates Maven to 3.9.3, as Tycho 4 requires at least 3.9.x.

Update Tycho from 3.0.4 to 4.0.0

---

org.eclipse.draw2d/src/org/eclipse/draw2d/parts/Thumbnail.java

The thumbnail is now using only the SWTGraphics and now scaled graphics anymore. Furthermore we stop now active updates of the thumbnail runable if during a repaint request it is running. 
@Phillipus I would be happy on your feedback. I've the slight feeling if the performance got worse with this change but not fully sure.

Reworked Thumbnail to not use scaled graphics anymore addresses #106

---

org.eclipse.draw2d/META-INF/MANIFEST.MF
org.eclipse.draw2d/src/org/eclipse/draw2d/parts/ScrollableThumbnail.java
org.eclipse.draw2d/src/org/eclipse/draw2d/parts/Thumbnail.java

The SourceFigure in the ScrollableThumbnail may be different then the viewport's content used. In that cases the size and position of the Selector was not handled correctly.
If the SourceFigure is the content of the viewport then it behaves as before.
@Phillipus @ptziegler  what do you think. For me it behaves now more correct and opens a nice use case for 4diac IDE, where I otherwise would need to copy the whole class, which I found not as nice.
With all the automatic clean-ups, the interesting lines are: 200, 204, 235, & 236.

Use SourceFigure for ScrollableThumbnail handling

---

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/ConnectionEndPointMoveTest.java
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/PaintDamageEraseTest.java
org.eclipse.draw2d/src/org/eclipse/draw2d/DeferredUpdateManager.java
org.eclipse.draw2d/src/org/eclipse/draw2d/FigureCanvas.java
org.eclipse.draw2d/src/org/eclipse/draw2d/UpdateListener.java
org.eclipse.draw2d/src/org/eclipse/draw2d/UpdateManager.java
org.eclipse.draw2d/src/org/eclipse/draw2d/parts/Thumbnail.java
org.eclipse.gef.examples.text/src/org/eclipse/gef/examples/text/tools/TextTool.java

This change adjusts the notifyPainting() method in UpdateListener and the firePainting() method in UpdateManager to expect a generic map of (IFigure, Rectangle) pairs, rather than a raw map.
This should not cause errors in client code, as calling or overwriting this method can still be done using a raw map (which will create a "unchecked or unsafe operations" warning).

Typify dirtyRegion map in UpdateListener and UpdateManager

---

org.eclipse.gef/src/org/eclipse/gef/commands/CompoundCommand.java
org.eclipse.gef/src/org/eclipse/gef/commands/ForwardUndoCompoundCommand.java

Addresses #155 
@Destrolaric @ptziegler as it is only changing GEF internals it shouldn't have any impact on users, or?

Typified command list on compound command. Cleaned-up compound command.

---

org.eclipse.draw2d/src/org/eclipse/draw2d/graph/CompoundHorizontalPlacement.java
org.eclipse.draw2d/src/org/eclipse/draw2d/graph/EdgeList.java
org.eclipse.draw2d/src/org/eclipse/draw2d/graph/GraphUtilities.java
org.eclipse.draw2d/src/org/eclipse/draw2d/graph/HorizontalPlacement.java
org.eclipse.draw2d/src/org/eclipse/draw2d/graph/LocalOptimizer.java
org.eclipse.draw2d/src/org/eclipse/draw2d/graph/NodeList.java
org.eclipse.draw2d/src/org/eclipse/draw2d/graph/PopulateRanks.java
org.eclipse.draw2d/src/org/eclipse/draw2d/graph/RankList.java
org.eclipse.draw2d/src/org/eclipse/draw2d/graph/SortSubgraphs.java
org.eclipse.draw2d/src/org/eclipse/draw2d/graph/VerticalPlacement.java

In addition implemented Iterable interface to allow forEach and ranged for loops on RankLists.
Addresses #155 
@ptziegler @Destrolaric this would be my last clean-up for the main draw2d graph classes

[Modernize Code] Use typed generics for RankList

---

org.eclipse.gef/plugin.xml

We found out that the wrong color was used for line foreground when grid is shown

fix wrong color for grid line foreground

---

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/graph/test/DirectedGraphLayoutTest.java
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/Draw2dTestSuite.java
org.eclipse.draw2d/src/org/eclipse/draw2d/graph/BreakCycles.java
org.eclipse.draw2d/src/org/eclipse/draw2d/graph/PopulateRanks.java

The for-each loop inside the BreakCycle method used to iterate over all graph nodes. This was wrongfully changed to a local variable which is initialized as an empty list.
The for-each loop inside PopulateRanks iterates over all graph nodes and calls VirtualNodeCreation internally. The constructor of this class, however, may add nodes to the graph, leading to a
ConcurrentModifcationException. To avoid this problem, we iterate of a local copy of the graph nodes instead.
Amends 31a70127f763d40fd1f6eb6a56de9158cf9538ce

Fix: Regressions caused by cleaning up BreakCycle & PopulateRanks

---

org.eclipse.draw2d/src/org/eclipse/draw2d/SWTGraphics.java

- On Windows hi-dpi calling GC#setLineAttributes will mean that lineattributes.width is increased by calling DPIUtil.autoScaleUp so we clone lineAttributes
- See https://github.com/eclipse/gef-classic/issues/248

Fix wrong line width on Windows hi-dpi

---

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/LocalOptimizerTest.java
org.eclipse.draw2d/src/org/eclipse/draw2d/graph/DirectedGraphLayout.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/DirectedGraphLayoutAlgorithm.java

By using a deque, we have access to both an iterator() and an descendingIterator() method. This allows us to iterate over the collection in both directions.

Typify internal list in DirectGraphLayout and convert to Deque

---

org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/Graph.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphDragSupport.java

Allow the Zest Graph to be more flexible and customizable
- exposed createLayers() method
- added creator method for ZestRootLayer (e.g. to change highlighting behavior)
- created super-interface and creator method for drag support.

Allow more customizable Zest Graph implementations

---

org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphConnection.java

if the already exposed createFigure method in GraphConnection is overridden, the connectionLabel will never be initialized and thus lead to a null pointer in the doUpdateFigure method.

added label initialization for graphconnection

---

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/Draw2dTestSuite.java
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/FigurePaintingTest.java
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/utils/TestFigure.java
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/utils/TestLogger.java
org.eclipse.draw2d/src/org/eclipse/draw2d/Figure.java

When updating the border or the background/foreground color of a figure,
it may happen what we whole figure is repainted, even though it hasn't
been modified.
Additional checks have been added to check for equality in the setter
methods, to limit the amount of times repaint() and revalidate() is
called.

Avoid excessive repaint operations when figure is not modified

---

org.eclipse.draw2d/src/org/eclipse/draw2d/Figure.java
org.eclipse.draw2d/src/org/eclipse/draw2d/IFigure.java

If a method only works on the IFigure interface, it currently has to either cast the object to a Figure, in order to be able to call getLocation() or instead go via getBounds().getLocation().
To avoid this issue, this method has been pulled to the implemented interface. A default implementation is used to for backwards compatibility. The implementation inside the Figure is not removed, in order to keep the 'final' modifier, but internally only calls the default implementation.
The interface already has a setter method for the location. Also providing a getter only seems natural.

Pull getLocation() method from Figure to IFigure interface.

---

.github/workflows/maven.yml

With Java 21 being the current LTS, we should ensure that GEF is forward compatible.

Compile and test GEF against both Java 17 and Java 21.

---

org.eclipse.gef/src/org/eclipse/gef/requests/GroupRequest.java
org.eclipse.gef/src/org/eclipse/gef/requests/SimpleFactory.java

For the GroupRequest class, we store the list of edit-parts as a List<? extends EditPart>, in order to support casting it to e.g. a List<CustomEditPart>.
For the SimpleFactory class, we replace the deprecated Class.newInstance() call with Constructor.newInstance(), to keep the compile-time exception checking (see JavaDoc for more details).

Typify GroupRequest and SimpleFactory classes

---

org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/LayoutAlgorithm.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/AbstractLayoutAlgorithm.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/DirectedGraphLayoutAlgorithm.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/HorizontalShift.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/RadialLayoutAlgorithm.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/SpringLayoutAlgorithm.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/TreeLayoutAlgorithm.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/internal/CycleChecker.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/internal/DynamicScreen.java

In order to reduce our warning count and increase typed generic use (Issue #155)  this PR typed all generics in the Zest Algorithms package. This reduced the warning count by ap. 200.

Cleaned Zest Algorithms

---

org.eclipse.draw2d/src/org/eclipse/draw2d/ColorConstants.java
org.eclipse.draw2d/src/org/eclipse/draw2d/Cursors.java

Creating the static standard platform cursors may lead to a potential memory leak, if the Cursors class ever happens to be unloaded, before the application is terminated (e.g. when the bundle is stopped), because this process won't free up the allocated resources.
To avoid this issue, we use Display.getSystemCursor, similar to what is done to get the standard platform colors.
Given that those factory methods are technically API, they have also been documented, with a large part taken from the getSystemCursor() and getSystemColor() JavaDoc.

Create system cursors using Display getSystemCursor method #286

---

org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/Rectangle.java

The intersects checking method of Rectangle used intersect with a copy of an rectangle. This generated a lot of garbage during drawing as intersect is used to check if a children should be drawn or not.
Addresses #282

Rework Rectangle.intersects so that it does not need to create a rect

---

org.eclipse.gef.examples.flow/src/org/eclipse/gef/examples/flow/policies/ActivityContainerHighlightEditPolicy.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/ContainerHighlightEditPolicy.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/LabelDirectEditPolicy.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/LogicNodeEditPolicy.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/LogicResizableEditPolicy.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/WireEndpointEditPolicy.java
org.eclipse.gef/META-INF/MANIFEST.MF
org.eclipse.gef/src/org/eclipse/gef/editpolicies/BendpointEditPolicy.java
org.eclipse.gef/src/org/eclipse/gef/editpolicies/ConnectionEndpointEditPolicy.java
org.eclipse.gef/src/org/eclipse/gef/editpolicies/FlowLayoutEditPolicy.java
org.eclipse.gef/src/org/eclipse/gef/editpolicies/GraphicalEditPolicy.java
org.eclipse.gef/src/org/eclipse/gef/editpolicies/LayoutEditPolicy.java
org.eclipse.gef/src/org/eclipse/gef/editpolicies/NonResizableEditPolicy.java
org.eclipse.gef/src/org/eclipse/gef/editpolicies/ResizableEditPolicy.java
org.eclipse.gef/src/org/eclipse/gef/editpolicies/ScrollableSelectionFeedbackEditPolicy.java
org.eclipse.gef/src/org/eclipse/gef/editpolicies/SnapFeedbackPolicy.java
org.eclipse.gef/src/org/eclipse/gef/editpolicies/XYLayoutEditPolicy.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/rulers/DragGuidePolicy.java

Java now allows overriding return values. Using this for GraphicalEditPolicy.getHost() reduces cast requirements and makes code clearer.

[Modernize Code] Type the return value of GraphicalEditPolicy getHost

---

Jenkinsfile

To avoid uploading the artifacts from old branches to the update site, we should make sure that we only do so, when on the master branch.

Only promote build results when on the master branch

---

Jenkinsfile

To avoid uploading the artifacts from old branches to the update site, we should make sure that we only do so, when on the master branch.

Only promote build results when on the master branch (#311)

---

org.eclipse.draw2d-feature/build.properties
org.eclipse.draw2d.sdk-feature/build.properties
org.eclipse.gef-feature/build.properties
org.eclipse.gef.examples-feature/build.properties
org.eclipse.gef.sdk-feature/build.properties
org.eclipse.zest-feature/build.properties
org.eclipse.zest.sdk-feature/build.properties

Both the GEF feature and the GEF bundle have the artifact id "org.eclipse.gef".
If both artifact have the same group id, they are considered to be the "same" artifact, from a Maven perspective.
Overwrite the group id for features to be "org.eclipse.gef.features", to make sure the generated Maven coordinates are distinct.
See #290

 Specify different group id for features to avoid collisions with bundles 

---

org.eclipse.draw2d/src/org/eclipse/draw2d/AutomaticRouter.java
org.eclipse.draw2d/src/org/eclipse/draw2d/internal/MultiValueMap.java

The MultiValueMap used to be backed by a map with either a list or a single object as value.
This part has been adapted so that the map always contains a list of values. While this adds a small overhead when filling the map, it should in return reduce the overhead when calling the getter for values with only a single element.
Reduces the total amount of warnings by ~20.

Typify MultiValueMap and fix warnings in AutomaticRouter

---

setup/GEF.setup

https://github.com/eclipse/gef-classic/issues/308

Fix GEF.setup .project creation to happen after git clone task

---

README.md

I've generalized the URL to a specific release, so that we don't have to update the ReadMe for every release.
Primarily because we've forgotten about it since 3.14 :P

Update links to p2 repositories in ReadMe file

---

org.eclipse.draw2d.tests/META-INF/MANIFEST.MF
org.eclipse.draw2d.tests/META-INF/services/java.text.spi.BreakIteratorProvider
org.eclipse.draw2d.tests/META-INF/services/org.eclipse.draw2d.text.BidiProvider
org.eclipse.draw2d.tests/pom.xml
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/BaseTestCase.java
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/BidiProcessorTest.java
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/ColorConstantTest.java
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/TextFlowWrapTest.java
org.eclipse.draw2d/META-INF/MANIFEST.MF
org.eclipse.draw2d/src/org/eclipse/draw2d/text/BidiProcessor.java
org.eclipse.draw2d/src/org/eclipse/draw2d/text/BidiProvider.java
org.eclipse.draw2d/src/org/eclipse/draw2d/text/FlowUtilities.java
org.eclipse.gef.examples.text/META-INF/MANIFEST.MF
org.eclipse.gef.examples.text/src/org/eclipse/gef/examples/text/edit/TextFlowPart.java

With this change, the FlowUtilities class uses the BreakIteratorProvider
to create its BreakIterator instances. This way, downstream project can
contribute their own implementations, if they don't want to use the
native Java implementation.
Similarly, a BidiProvider class is created, to support a custom Bidi
implementation in the BidiProcessor class.
Resolves #289

Add ability to contribute custom BreakIterator/Bidi via SPI

---

org.eclipse.draw2d/src/org/eclipse/draw2d/Figure.java
org.eclipse.draw2d/src/org/eclipse/draw2d/FigureCanvas.java
org.eclipse.draw2d/src/org/eclipse/draw2d/PrintOperation.java
org.eclipse.draw2d/src/org/eclipse/draw2d/ScrollBarLayout.java
org.eclipse.draw2d/src/org/eclipse/draw2d/ScrollPaneSolver.java
org.eclipse.draw2d/src/org/eclipse/draw2d/ToggleButton.java
org.eclipse.draw2d/src/org/eclipse/draw2d/Triangle.java
org.eclipse.draw2d/src/org/eclipse/draw2d/text/BlockFlow.java
org.eclipse.gef/src/org/eclipse/gef/editparts/ViewportAutoexposeHelper.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/PaletteScrollBar.java

Rectangle's crop() and getCropped() methods are deprecated and shrinked and getShrinked should be used instead. All usages have been updated.
Addresses #21

Removed usage of deprecated rectangle functions

---

org.eclipse.draw2d/src/org/eclipse/draw2d/ShortestPathConnectionRouter.java
org.eclipse.draw2d/src/org/eclipse/draw2d/graph/ShortestPathRouter.java

The shortest path router return a list of the routed paths. The change to a wildcard extend return was over pessimistic as Path is a class not to be extended. Therefore the list is now a list of Paths.
Addresses #155.
This fixes also a compile issue in GMF runtime: @pcdavid @ptziegler

Fix path list return value for shortest path router

---

org.eclipse.gef/src/org/eclipse/gef/ui/parts/GraphicalEditor.java

Remove the ActionIDList and instead clearly define that the Action lists for selection, stack and property Actions can only hold Strings.
Addresses #155 
This PR may break client code if the lists where used wrongly.

[Modernize Code] Typify GraphicalEditor Action Lists

---

setup/GEF.setup

The set of IUs between GEF FX and GEF Classic are not unique, so more care must be taken to avoid resolving the GEF FX IUs with higher version into the target platform.  Furthermore, GEF Classic does not even require an Orbit repo to resolve the target platform; purely the Platform SDK is sufficient.
https://github.com/eclipse/gef-classic/issues/352

Remove the repository containing GEF FX from the targlet in the setup

---

org.eclipse.gef/src/org/eclipse/gef/SharedCursors.java

See https://github.com/eclipse/gef-classic/issues/354
On Mac and Linux X11 device zoom should always be 100% when creating the ImageData for the cursor.

Fix cursors double-size on Mac and Linux 11

---

org.eclipse.draw2d/src/org/eclipse/draw2d/ToolTipHelper.java

The hide delay for tooltips in Draw2d is currently fixed to 5 seconds. The value can only be changed for a speific `ToolTipHelper`, which in turn is tied to a specific control. There is option to configure this delay globally.
With this change, the default value for the hide delay can globally be changed on the `ToolTipHelper` class, such that subsequent tooltip creations will use this value as default.
One could also think about more general configuration options, such as providing a system property, to make this delay configurable without a dependency to Draw2d. But since the demand for this configuration options does not seem to be high, I would expect the proposed lightweight realization to be sufficient (at least for us).

Make default hide delay for tooltip configurable

---

CHANGELOG.md
org.eclipse.draw2d.doc.isv/META-INF/MANIFEST.MF
org.eclipse.draw2d.doc.isv/guide-src/extensions.adoc
org.eclipse.draw2d.doc.isv/guide-src/guide.adoc
org.eclipse.draw2d.doc.isv/guide-src/migration-guide.adoc
org.eclipse.draw2d.doc.isv/pom.xml
org.eclipse.draw2d.doc.isv/topics_Guide.xml

We switched from the Bidi and BreakIterator implementation contributed by com.ibm.icu to the native Java implementation.
Because those implementations are not 100% compatible, we should note this in the changelog and also inform users about how they may be able to contribute their own implementation.

Update documentation regarding ICU removal

---

org.eclipse.draw2d.doc.isv/pom.xml
org.eclipse.gef.doc.isv/pom.xml
org.eclipse.zest.doc.isv/pom.xml

This disables the Ant task (when inside the IDE) that is responsible for collecting the JavaDoc that is used by the online help. Reason being that its dependent "copy-resource" task isn't executed, leading to errors in a clean workspace.
Amends 60c6b5cda78241603ef99cc4ded08921f17cdaeb

Disable generation of JavaDoc as part of the incremental build

---

org.eclipse.gef/src/org/eclipse/gef/palette/PaletteContainer.java
org.eclipse.gef/src/org/eclipse/gef/palette/PaletteGroup.java
org.eclipse.gef/src/org/eclipse/gef/palette/PaletteStack.java
org.eclipse.gef/src/org/eclipse/gef/palette/PaletteToolbar.java

In the last clean-up a non back-wardscompaptible interface change was introduced. This commit fixes that.

Relax demands on PaletteContainer addAll Methods.

---

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/Draw2dTestSuite.java
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/FanRouterTest.java
org.eclipse.draw2d/src/org/eclipse/draw2d/FanRouter.java

This commit partially reverts fd75841fd7e0638c18827f203257e504536fb15e and uses PrecisionPoints instead of Points in the FanRouter class, to store the bend point.
Note that because the mid point is a plain point, the equality check is done using the integer coordinates.
Resolves #383

Use PrecisionPoint instead of Point to handle deprecation warning

---

org.eclipse.draw2d/src/org/eclipse/draw2d/Container.java
org.eclipse.gef.examples.flow/src/org/eclipse/gef/examples/flow/figures/SubgraphFigure.java
org.eclipse.gef.examples.flow/src/org/eclipse/gef/examples/flow/parts/ActivityDiagramPart.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/PaletteStackEditPart.java

Using pure Figure just as layout container for other figures is very heavy weight as the graphics state is saved and restored very often. For pure layout containers this would not be necessary. This new figure can help to reduce memory footprint and drawing performance for these cases.

Added new Figure Container to serve as light weight drawing container

---

org.eclipse.zest.core/src/org/eclipse/zest/core/viewers/internal/AbstractStructuredGraphViewer.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphNode.java

The selection of an abstract viewer can either be of type GraphNode or GraphConnection. However, this list of items is explicitly casted to an array of GraphNodes. Use the common base class GraphItem instead.
Furthermore, the viewer attempts to remove the objects of type GraphConnection from the layout manager, whenever a node is removed. But the layout manager only accepts objects of type LayoutRelationship which is a member of the GraphConnection.

Handle implicit ClassCastException in Zest Core due to raw types

---

pom.xml

The package-plugin mojo can't be executed within the Eclipse. Attempting to do only creates an error marker in the isv bundles.

Disable execution of tycho-packaging-plugin in Eclipse IDE

---

org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/AbstractLayoutAlgorithm.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/progress/ProgressListener.java
org.eclipse.zest.tests/src/org/eclipse/zest/tests/LayoutAlgorithmTest.java

An exception might be thrown if a listener is remove when e.g. a ProgressEnded event is fired. Perform the notification on a local copy of the internal list of listeners instead.
Resolves https://github.com/eclipse/gef-classic/issues/398

Fix ConcurrentModificationException in Zest SimpleSWTExample

---

org.eclipse.gef/src/org/eclipse/gef/palette/PaletteContainer.java
org.eclipse.gef/src/org/eclipse/gef/ui/palette/PaletteCustomizer.java
org.eclipse.gef/src/org/eclipse/gef/ui/palette/customize/PaletteContainerFactory.java
org.eclipse.gef/src/org/eclipse/gef/ui/palette/customize/PaletteCustomizerDialog.java
org.eclipse.gef/src/org/eclipse/gef/ui/palette/customize/PaletteTreeProvider.java
org.eclipse.gef/src/org/eclipse/gef/ui/palette/editparts/PaletteEditPart.java

Downstream projects may declare their own custom palette entries. By returning a list of PaletteEntry's, it's no longer possible to cast this list of those custom entries.
Resolves https://github.com/eclipse/gef-classic/issues/401

Relax demands on PaletteContainer getChildren() method

---

README.md

The GEF website is no longer accessible and the last state only contained references to GEF FX. The old pages have been migrated to the GitHub wiki.
See https://github.com/eclipse/gef-classic/discussions/411

Update dead links in ReadMe file

---

org.eclipse.draw2d/src/org/eclipse/draw2d/FigureCanvas.java

The reworked scrolling of the FigureCanvas didn't correctly calculated the exposure areas which need to be redrawn after scrolling. This led to drawing artifacts.

Scroll redraw on Windows lead to drawing artifacts

---

org.eclipse.draw2d/src/org/eclipse/draw2d/XYLayout.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/rulers/RulerLayout.java

`RulerLayout` inherited from `XYLayout`. The later assumed that children constraint are rectangles. As this is not valid for `RulerLayout`s the `RulerLayout` was changed to inherit from `AbstractLayout` and use its own constraint map with Integers.
Fixes #418

Changed RulerLayout to directly inherit from AbstractLayout  #418

---

org.eclipse.draw2d/src/org/eclipse/draw2d/FigureCanvas.java

Fix for eclipse#425. Detect when overlay scrolling is enabled on GTK and it's the case then ignore scrollbar trims when calculating the viewport client area.
This fix tackles the immediate performance issue however it adds a platform dependency (which isn't the first in GEF), but also is not future proof because the upcoming GEF4 removes the GTK_OVERLAY_SCROLLING environment variable support which is being checked here. Since SWT doesn't provide a way to test for GTK version, a more complete fix would involve a better support for GTK_OVERLAY_SCROLLING in SWT's Scrollable.getScrollbarsMode() method.

Fix redraw performance issues in FigureCanvas when GTK overlay scrolling is enabled (eclipse#425)

---

org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/TreeLayoutAlgorithm.java

Can be reproduced using the GraphJFaceSnippet6. The problem occurs because a size() == 0 check has been wrongfully replaced with a !isEmpty().
See https://github.com/eclipse/gef-classic/issues/443 Amends 2e860acc0b2e1e8847408141e00f787ee3aee9c1

Fix: Graph nodes using the tree layout have an empty size.

---

org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphNode.java

When the constructors in the GraphNode class have been unified, we wrongfully pass "graphModel.getGraph()" as an argument instead of the current container. This causes all nodes to be added to the parent graph.
See the UML example for reference. One of the class diagrams should be contained by the UML container, but all three are part of the parent graph instead.
Amends a13541fd21b23c8fdfb5c64a99321f7b8be44706

Fix: Adding a node to a graph container adds it to the graph instead

---

org.eclipse.gef.tests/src/org/eclipse/gef/test/GEFTestSuite.java
org.eclipse.gef.tests/src/org/eclipse/gef/test/GraphicalViewerTest.java
org.eclipse.gef/src/org/eclipse/gef/SelectionManager.java

The selection inside a GEF viewer is assumed to always be non-null. But
because the (implicit) null check is done after the editpart is added to
the internal list, it leaves the viewer in an inconsistent state.
To avoid this, the null check is done earlier, so that the exception is
thrown before the internal model is modified.

Move up null check in GEF viewer when the selected editpart is updated.

---

org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphConnection.java

This example has a special situation where the connection figure is the same object as the source and target container connection figure. Because the connection figure is disposed first, the parent of those other objects is already null, leading to an exception.

Fix NullPointerException when closing GraphSnippet13

---

org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphConnection.java

The local variables should be cleared when the figure is removed, even if either of the containers has already been disposed.
Amends 2288625a8c910773a4e3076691b39ad3c13a2cc8

Set source/target container figure to null after Zest connection removal

---

org.eclipse.draw2d-feature/feature.xml
org.eclipse.draw2d.sdk-feature/feature.xml
org.eclipse.draw2d/META-INF/MANIFEST.MF
org.eclipse.gef-feature/feature.xml
org.eclipse.gef.examples-feature/feature.xml
org.eclipse.gef.sdk-feature/feature.xml
org.eclipse.gef/META-INF/MANIFEST.MF
org.eclipse.zest-feature/feature.xml
org.eclipse.zest.core/META-INF/MANIFEST.MF
org.eclipse.zest.examples/META-INF/MANIFEST.MF
org.eclipse.zest.layouts/META-INF/MANIFEST.MF
org.eclipse.zest.sdk-feature/feature.xml
target-platform/GEF_classic.target

@azoitl 
FYI, I looked into this obscure "The minor version should be incremented in version x.y.z, since execution environments have been changed since version x.y.z" error and I'm fairly confident that this is an issue within Equinox.
In short, the API tool is unable to load the execution environment of the baseline plugins because Equinox ignores the "Require-Capability" header (at least for loading the EE). And therefore, an empty string is compared to the execution environment that is set in the workspace (JavaSE-17), which is therefore marked as an error.

Update feature and plugin version numbers for 3.21 release cycle

---

org.eclipse.draw2d/src/org/eclipse/draw2d/FigureCanvas.java

The value returned by getClientArea() might not match the physical size of the canvas. Therefore it might happen that parts of the canvas are hidden behind a scrollbar or not painted at all.
Resolves https://github.com/eclipse/gef-classic/issues/456

Use rectangle from ScrollPaneSolver as client area for root figure

---

org.eclipse.gef.tests/src/org/eclipse/gef/test/CommandStackTest.java
org.eclipse.gef/src/org/eclipse/gef/commands/CommandStack.java

Use a CopyOnWriteArrayList instead of a plain ArrayList for storing the registered listeners. Adding or removing from this list always results in a fresh copy of the underlying array, avoiding concurrent modification.
Assuming that the number of times an event is fired far outweighs the times a listener is added and/or removed, this should be more efficient than creating a copy of the listeners, whenever the notify method is called.
Resolves https://github.com/eclipse/gef-classic/issues/454

Fix: ConcurrentModificationException in CommandStack

---

org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/rulers/LogicRulerProvider.java
org.eclipse.gef/src/org/eclipse/gef/rulers/RulerProvider.java

Use a thread-safe CopyOnWriteArrayList instead of a plain ArrayList for
storing all registered listeners. Note that writing to this type is
expensive, as the array is copied on every add. But for this use case,
the number of listeners should be negligible.
To reproduce: Enable the ruler in the Logic example and create a new
guide.

Fix ConcurrentModificationException in RulerProvider

---

org.eclipse.gef.tests/src/org/eclipse/gef/test/swtbot/FlowDiagramTests.java
org.eclipse.gef/src/org/eclipse/gef/tools/MarqueeSelectionTool.java

This commit partially reverts d94c624c8cd5b92b0568ac416bc400d68fe0ed7a. When e.g. moving the mouse cursor out and back in the editor, the tool is not properly reactivated.
Reason being that this only happens when the currently selected editor is graphical viewer. But because the editor is still null (as it is set to null when leaving the editor), this check always returns false.
The change was seemingly done as an optimization and is not relevant for the actual commit. So it should be save to rroll it back.
Resolves https://github.com/eclipse/gef-classic/issues/466

Fix: Marquee Selection Tool causes unresponsive UI

---

org.eclipse.draw2d/src/org/eclipse/draw2d/PopUpHelper.java

If a workbench part is detached and a tooltip is initially displayed, when the part is re-attached the parent Shell is disposed which in turn disposes of the PopupHelper's Shell. This will lead to an SWT Error when the Shell is accessed again.
To fix this, create the PopupHelper Shell with the Control's Display instead of its Shell.
See https://github.com/eclipse/gef-classic/issues/469

Fix possible SWTException "Widget is disposed" exception when displaying a Tooltip

---

org.eclipse.draw2d/src/org/eclipse/draw2d/Animation.java
org.eclipse.draw2d/src/org/eclipse/draw2d/NativeGraphicsSource.java
org.eclipse.zest.tests/src/org/eclipse/zest/tests/examples/AbstractGraphTest.java
org.eclipse.zest.tests/src/org/eclipse/zest/tests/examples/GraphSWTTests.java

When the FigureCanvas is created with SWT.DOUBLE_BUFFERED, animations are not painted correctly. This is because an instance of NativeGraphicsSource is used internally, which doesn't paint synchronously.
Because the animation is done inside the UI thread, this paint operation is only processed after the animation is done.
Resolves https://github.com/eclipse/gef-classic/issues/376

Force repaint in NativeGraphicsSource to fix broken animation

---

org.eclipse.draw2d/src/org/eclipse/draw2d/Animation.java
org.eclipse.draw2d/src/org/eclipse/draw2d/NativeGraphicsSource.java
org.eclipse.zest.tests/src/org/eclipse/zest/tests/examples/AbstractGraphTest.java
org.eclipse.zest.tests/src/org/eclipse/zest/tests/examples/GraphSWTTests.java

Because animations are drawn again, the SWTBot tests check the state of the editor before the animation has finished.
This reverts commit ee7f7eed4ed1544bd4ddc4ad92e8f3986e939947.

Revert "Force repaint in NativeGraphicsSource to fix broken animation"

---

.github/workflows/issues.yml
.github/workflows/maven.yml
.github/workflows/unit-tests.yml

If a version only contains the major version, Dependabot ignores any minor or micro releases. Furthermore, by using the commit hash instead of the version, we decrease the risk of supply-chain attacks, as tags aren't immutable and malicious user may re-tag a release containing harmful content.
Resolves https://github.com/eclipse/gef-classic/issues/471

Update GitHub workflow actions to their latest versions

---

org.eclipse.draw2d.doc.isv/.classpath
org.eclipse.draw2d.doc.isv/.project
org.eclipse.gef.doc.isv/.classpath
org.eclipse.gef.doc.isv/.project
org.eclipse.zest.doc.isv/.classpath
org.eclipse.zest.doc.isv/.project

Those bundles only contain the AsciiDoc files for the online help, but no actual Java files. It therefore doesn't make sense for them to have the Java nature.
Instead, the project receive the Plugin nature, in order to enable e.g. the validation of the Manifest file.

Remove unnecessary Java nature from isv bundles

---

org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/Dimension.java
org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/Point.java
org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/PrecisionDimension.java
org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/PrecisionPoint.java
org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/PrecisionRectangle.java
org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/Ray.java
org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/Rectangle.java

This marks all fields, methods, constructors and classes which have been marked as deprecated as "for-removal", to be deleted or made private in a future release.

Mark deprecated elements in Draw2D Geometry component as "for Removal"

---

org.eclipse.gef/src/org/eclipse/gef/SharedCursors.java
org.eclipse.gef/src/org/eclipse/gef/internal/InternalGEFPlugin.java
org.eclipse.gef/src/org/eclipse/gef/ui/palette/FlyoutPaletteComposite.java

The cursors used in the flyout palette only exist for the default 100%. If a system is using a higher zoom level, the creation of those cursors fails with an IllegalArgumentException. Instead, we should scale the cursor image to match the current level.
Instead of reading the zoom level only once, it is now calculated dynamically, as the zoom may change depending on the display or because it has been changed. The methods for handling this case have also been moved from the SharedCursors class to the InternalGEFPlugin, so that it becomes available to the DragCursors class.
From there, we call asImageDataProvider() to convert the image descriptor to image data which internally scales the image via DPIUtil magic, if necessary.
See https://github.com/eclipse/gef-classic/issues/464

Fix errors in drag cursors when using high-DPI screens

---

org.eclipse.draw2d/src/org/eclipse/draw2d/Figure.java

The Figure#remove() method throws a NullPointerException when trying to remove a "null" child, due to a call to figure.getParent(). To remain consistent with the case where the child belongs to a different parent, this should also throw an IllegalArgumentException.

Throw IllegalArgumentException when removing null child from figure

---

org.eclipse.gef.examples.digraph1/src/org/eclipse/gef/examples/digraph1/editpart/Digraph1GraphEditPart.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/LogicContainerEditPart.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/LogicContainerTreeEditPart.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/LogicDiagramEditPart.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/LogicTreeEditPart.java
org.eclipse.gef/src/org/eclipse/gef/editparts/AbstractEditPart.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/rulers/RulerEditPart.java
org.eclipse.gef/src/org/eclipse/gef/rulers/RulerProvider.java

To reduce the number of warnings a bit more getModelChildren has now a type. Has little impact on the code.
https://github.com/eclipse/gef-classic/issues/155

Add type to getModelChildren #155

---

org.eclipse.draw2d.examples/META-INF/MANIFEST.MF
org.eclipse.draw2d.examples/sandbox/gef/bugs/BugWithLocalCoordinateSystem.java
org.eclipse.draw2d.tests/META-INF/MANIFEST.MF
org.eclipse.draw2d.tests/pom.xml
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/swtbot/AbstractSWTBotTests.java
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/swtbot/FigureTest.java
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/swtbot/SWTBotTestSuite.java
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/utils/Snippet.java
org.eclipse.draw2d/src/org/eclipse/draw2d/Figure.java

A figure using local coordinates translates the given point for its children at the beginning of findMouseEventTargetInDescendantsAt(int, int). However, during iteration over its children, the translated point is stored in a  static variable PRIVATE_POINT. The value would be changed by a child, if the child also uses local coordinates. This affects the following queries to the rest of children, if no figure is found under that child.
Fixes https://github.com/eclipse/gef-classic/issues/495

Bug 226103 - findMouseEventTargetAt problem with local coordinate system

---

org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/progress/ProgressListener.java

The ProgressListener has been marked as deprecated and is no longer supported in Zest 2.0. Meaning the stub implementation also needs to be marked as such, in order to propagate the removal warning.

[Zest 2.0] Mark stub-implementation of ProgressListener as for-removal

---

org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/SpaceTreeLayoutAlgorithm.java

This resolves the "raw-type" warning related to the list of SpaceTreeLayer(s). The complete refactoring is split into multiple commits, in order to keep the individual changes isolated.

[Zest 2.0] Cleanup compiler warnings in SpaceTreeLayoutAlgorithm (pt1)

---

org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/HorizontalShiftAlgorithm.java

Resolves compiler warning regarding the usage of raw lists when handling the rows of entities.

[Zest 2.0] Cleanup compiler warnings in HorizontalShiftAlgorithm

---

org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/DirectedGraphLayoutAlgorithm.java

This removes the duplicate ExtendedDirectedGraphLayout class (with the original Zest 1.0 class being used instead, as the Zest 2.0 class doesn't do anything...). Resolves the raw-type warnings when calling applyLayout(boolean) as well as some minor cleanup.

[Zest 2.0] Cleanup compiler warnings in DirectedGraphLayoutAlgorithm

---

org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/LayoutAlgorithm.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/LayoutEntity.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/LayoutGraph.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/LayoutIterationEvent.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/NestedLayoutEntity.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/AbstractLayoutAlgorithm.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/GridLayoutAlgorithm.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/RadialLayoutAlgorithm.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/TreeLayoutAlgorithm.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/dataStructures/InternalNode.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/dataStructures/InternalRelationship.java

Primarily related to the references of deprecated classes marked as for-removal as well as the usage of raw types in the Zest 1.0 API. Where possible, the warnings have been resolved properly as best as possibles. But whenever this touches public API, we simply suppress the warning.
Given that this API will be removed in an upcoming release, the focus should be on stability and to avoid any incompatibilities that might arise from using the actual rather than raw types.

[Zest 2.0] Resolve Zest 1.0-related compiler warnings

---

org.eclipse.zest.layouts/.settings/.api_filters

Because the LayoutAlgorithm interface is annotated with "noimplement" and "noextend", a warning is produced for the classes that implement it.
But this is only relevant for clients, not the classes within Zest, so we simply suppress this warning.

[Zest 2.0] Create API filter for classes implementing LayoutAlgorithm

---

org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/InternalNodeLayout.java

Effectively just usage of raw types when dealing with graph layouts, widgets and figures.

[Zest 2.0] Cleanup compiler warnings in InternalLayoutContext

---

org.eclipse.zest.core/.settings/.api_filters
org.eclipse.zest.core/src/org/eclipse/zest/core/viewers/AbstractStructuredGraphViewer.java
org.eclipse.zest.core/src/org/eclipse/zest/core/viewers/GraphViewer.java
org.eclipse.zest.core/src/org/eclipse/zest/core/viewers/internal/AbstractStylingModelFactory.java
org.eclipse.zest.core/src/org/eclipse/zest/core/viewers/internal/GraphItemStyler.java
org.eclipse.zest.core/src/org/eclipse/zest/core/viewers/internal/GraphModelEntityFactory.java
org.eclipse.zest.core/src/org/eclipse/zest/core/viewers/internal/GraphModelFactory.java

A lot of methods have been marked as deprecated & for-removal due to the new Zest 2.0 API. Because those methods can't be deleted yet due to backwards compatibility, we simply suppress those warnings.

[Zest 2.0] Cleanup compiler warning in Zest graph viewer

---

org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/internal/ZestRootLayer.java

Objects and raw types where are used when dealing with the nodes and their decorations, rather than the IFigures.

[Zest 2.0] Cleanup compiler warnings in ZestRootLayer

---

org.eclipse.zest.core/.settings/.api_filters
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/Graph.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphContainer.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/IContainer.java

There are several instances where raw types are used instead of the GraphNode and GraphConnection widgets. Several private method can be marked as static.
The warnings caused by usage of the deprecated Zest 1.0 API have been suppressed, as those are needed for backwards compatibility to e.g. apply layouts using the old layout algorithms.

[Zest 2.0] Cleanup compiler warnings in GraphContainer

---

org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphContainer.java

This can be observed when using the ZoomSnippet with the Zest 2.0 layouts; The nodes inside the containers arent't aligned according to the RadialLayoutAlgorithm but instead all placed in the top-left corner.
This is because we call applyLayout(false), which is a no-op operation for this algorithm.
One can reproduce this issue by checking the ZoomSnippet, where the nodes inside the containers are not position correctly, after expanding the container.

[Zest 2.0] Fix: Layout inside GraphContainers is not applied correctly.

---

org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/BoxLayoutAlgorithm.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/DirectedGraphLayoutAlgorithm.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/SugiyamaLayoutAlgorithm.java

The SWT class provides perfectly fine constants. There is no need for us to re-define those constants when we can simply reuse them.

[Zest 2.0] Fix: Use SWT constants for horizontal and vertical alignment

---

org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/Graph.java

Because the layout algorithm is executed asynchronously, it may happen that the layout is performed AFTER the graph has been disposed. Explicitly check the state of the graph to avoid this issue.
This issue can easily be reproduced by opening and closing one of the snippets.

[Zest 2.0] Fix: WidgetIsDisposedException  when applying graph layout

---

org.eclipse.draw2d/src/org/eclipse/draw2d/ToolTipHelper.java

The pop-up helper reuses the shell that is used to display the tooltip. When a new tooltip is shown, the (currently invisible) shell is moved from its old location and then made visible. This doesn't work in GTK and the shell remains at its old location.
After the shell has been made visible, it is checked whether the shell has been correctly moved and if necessary, the shell coordinates are updated again. Note that it is still necessary to set the bounds while the shell is invisible, in order to properly handle the first tooltip that is shown.
Resolves https://github.com/eclipse/gef-classic/issues/531

Fix: ToolTipHelper doesn't work properly on Linux

---

org.eclipse.zest.core/.settings/.api_filters

The class is referencing old Zest 1.0 methods for the sake of backwards compatibility. Given that those methods should no longer be used, they therefore produce a corresponding API warning.
Because usage is intentional with no Zest 2.0 counterpart, we simply suppress those warnings.

[Zest 2.0] Fix API warnings in GraphConnection class

---

org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphNode.java

The constructors where one could pass the data object has been marked for removal as part of the Zest 2.0 migration, with the suggestion to call setData() afterwards.
However, this might not be possible for e.g. the CGraphNode, where the data object is returned by a call to createFigureForModel(), which then leads to an exception if this field hasn't been initialized yet.
To remedy this situation, the constructors expecting a raw object as data remain deprecated and instead a new constructor has been created, where this object has to be of type IFigure.

[Zest 2.0] Fix: Deprecation warnings in GraphNode constructor

---

org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/DefaultSubgraph.java

This primarily cleans up the mapping of the LayoutContext to its sub graph in the DefaultSubgraphFactory and PrunedSuccessorsSubgraphFactory.
In addition, some minor cleanup has been done when dealing with the node layouts, as well as on the refreshConnectionsVisibility() method.

[Zest 2.0] Cleanup raw type warnings in DefaultSubgraph

---

org.eclipse.zest.core/src/org/eclipse/zest/core/viewers/AbstractStructuredGraphViewer.java
org.eclipse.zest.core/src/org/eclipse/zest/core/viewers/AbstractZoomableViewer.java
org.eclipse.zest.core/src/org/eclipse/zest/core/viewers/GraphViewer.java
org.eclipse.zest.core/src/org/eclipse/zest/core/viewers/internal/GraphItemStyler.java
org.eclipse.zest.core/src/org/eclipse/zest/core/viewers/internal/GraphModelEntityRelationshipFactory.java
org.eclipse.zest.core/src/org/eclipse/zest/core/viewers/internal/SharedMessages.java
org.eclipse.zest.core/src/org/eclipse/zest/core/viewers/internal/messages.properties
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/DAGExpandCollapseManager.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/DefaultSubgraph.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/Graph.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphConnection.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphContainer.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphNode.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/HideNodeHelper.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/InternalLayoutContext.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/InternalNodeLayout.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/PrunedSuccessorsSubgraph.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/custom/LabelSubgraph.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/custom/TriangleSubgraph.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/internal/AspectRatioFreeformLayer.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/internal/ExpandGraphLabel.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/internal/GraphLabel.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/internal/NodeSearchDialog.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/internal/XYScaledGraphics.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/internal/ZestRootLayer.java

Classes such as the NodeSearchDialog use translatable strings while other classes which use them as internal values simply suppress the warning.

[Zest 2.0] Resolve remaining i18n warnings in Zest Core

---

org.eclipse.zest.core/.settings/.api_filters
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/Graph.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphConnection.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphContainer.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphNode.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/IContainer2.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/InternalNodeLayout.java

The IContainer2 interface expects the GraphContainer and Graph class to return the package-private InternalLayoutContext when calling getLayoutContext().
This doesn't work if this interface is used outside the Zest package (e.g. in our tests) and prevents its from being implemented by clients. Instead, we return the public LayoutContext interface, with a via to access the package-private instance by calling
internalGetLayoutContext().
Where necessary, the layout context is cast to its internal type, when its not clear whether the parent container is a Graph or a GraphContainer. Because of this, the getLayoutContext() have been made final.

[Zest 2.0] Resolve compiler warnings in Graph & friends

---

org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/HorizontalLayoutAlgorithm.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/HorizontalTreeLayoutAlgorithm.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/VerticalLayoutAlgorithm.java

The HorizontalTreeLayoutAlgorithm is already implemented by the base TreeLayoutAlgorithm class by using LEFT_RIGHT and the Horizontal-/VerticalLayoutAlgorithm is implemented by the BoxLayoutAlgorith with either SWT.HORIZONTAL or SWT.VERTICAL

[Zest 2.0] Reference replacement classes in deprecated layout algorithms

---

org.eclipse.draw2d.examples/sandbox/gef/bugs/BugWithLocalCoordinateSystem.java

The test for the BugWithLocalCoordinateSystem snippet may dispose the Display instance also hosting the Eclipse IDE. This may cause unintended side-effects, as the IDE is also terminated by the shutdown routine of the test suite.

Try to stabilize Draw2D SWTBot test

---

org.eclipse.draw2d/src/org/eclipse/draw2d/PopUpHelper.java
org.eclipse.draw2d/src/org/eclipse/draw2d/SWTEventDispatcher.java

This reverts 843e56c0df42aec34a487b97483a0b6c866fff95 and instead checks for a disposed Shell in SWTEventDispatcher#getToolTipHelper()
See https://github.com/eclipse/gef-classic/issues/555

Fix regression in Tooltip parent Shell on Linux Wayland

---

Jenkinsfile

This is required to avoid excessive disk usage.
This setting should be copied to the Jenkinsfiles in all project repos.

Restrict the number of builds to keep with artifacts

---

org.eclipse.draw2d/src/org/eclipse/draw2d/Figure.java

See https://github.com/eclipse/gef/issues/120

Use CopyOnWriteArrayList in LayoutNotifier

---

README.md

The URL still points to the "old" repository, containing builds up to
2023-12.

Update path to snapshot repository in set-up guide

---

org.eclipse.zest.core/src/org/eclipse/zest/core/viewers/GraphViewer.java

The state of the "dynamic layout" flag should be restored after the viewer input has changed, rather than always be set again. This flag can only be "false" if explicitly unset by the user. It should therefore remain disabled until explicitly enabled again.

Preserve dynamic layout flag after changing viewer input

---

org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/InternalNodeLayout.java
org.eclipse.zest.tests/src/org/eclipse/zest/tests/examples/GraphSWTTests.java

The location of the graph node should match whatever has been calculated in the layout algorithm and should not include the node size.

Fix bogus calculation of graph node location

---

org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/AlgorithmHelper.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/GridLayoutAlgorithm.java

The location of a node describes its top-left pixel, rather than its center. When using layout algorithms that are based on the grid layout, this causes the offset to be half the space between the rows and columns plus the half the width and height of the nodes.
Latter is undesirable and may cause nodes to be partially moved outside the client area.
The same issue can be observed in the other layout algorithms (Spring/Tree/Radial) when fitting the nodes into the client area, because the same mistake is repeated in the AlgorithmHelper class.

[Zest 2.0] Ignore node size when calculating position in layout

---

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/PointTests.java
org.eclipse.draw2d/META-INF/MANIFEST.MF
org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/Point.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/NodeFigure.java
org.eclipse.gef/src/org/eclipse/gef/editpolicies/BendpointEditPolicy.java

Having the squared distance between two points can be used often for simple sorting of points. It is more efficient then calculating the real distance. However the old getDistanc2's name was not very intuitive. With this change we have an appropriate replacement.
Addresses https://github.com/eclipse/gef-classic/issues/21

Introduce getDistanceSquared for deprecated getDistance2 #21

---

org.eclipse.gef/src/org/eclipse/gef/EditPartViewer.java
org.eclipse.gef/src/org/eclipse/gef/ui/parts/AbstractEditPartViewer.java
org.eclipse.gef/src/org/eclipse/gef/ui/parts/GraphicalViewerImpl.java

https://github.com/eclipse/gef-classic/issues/155

Added type information to getVisualPartMap #155

---

org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/actions/IncrementDecrementAction.java
org.eclipse.gef/.settings/.api_filters
org.eclipse.gef/META-INF/MANIFEST.MF
org.eclipse.gef/src/org/eclipse/gef/ui/actions/AlignmentAction.java
org.eclipse.gef/src/org/eclipse/gef/ui/actions/DeleteAction.java
org.eclipse.gef/src/org/eclipse/gef/ui/actions/DirectEditAction.java
org.eclipse.gef/src/org/eclipse/gef/ui/actions/MatchSizeAction.java
org.eclipse.gef/src/org/eclipse/gef/ui/actions/PasteTemplateAction.java
org.eclipse.gef/src/org/eclipse/gef/ui/actions/SelectionAction.java

The new method filters the selection given to the SelectionAction on EditParts. This can reduce the effort for implementing SelectionActions and at least makes them clearer.
Addresses: https://github.com/eclipse/gef-classic/issues/155

Added getSelectedEditParts to SelectionAction #155

---

org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/internal/XYScaledGraphics.java

Both ScaledGraphics and XYScaledGraphics share the same Graphics instance. Overwriting methods such as getAlpha(), which simply delegate to this Graphics object, are therefore unnecessary.

Remove redundant methods in XYScaledGraphics

---

org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/DrawerFigure.java

By moving the paint operation from the paintFigure() method out of the DrawerFigure class and instead doing so via the paintBackground() method of a custom implementation of the AbstractBackground class, clients can override the default background without having to extend the internal DrawerFigure class.

Move painting of DrawerFigure background to custom border class.

---

org.eclipse.zest.cloudio/src/org/eclipse/zest/cloudio/TagCloud.java

Several SWT resources are created but not propertly disposed in time. Easily reproducible via the example project.

Fix obvious resource leak in Cloudio viewer

---

CHANGELOG.md
org.eclipse.gef.examples.shapes/META-INF/MANIFEST.MF
org.eclipse.gef.examples.shapes/build.properties
org.eclipse.gef.examples.shapes/fragment.e4xmi
org.eclipse.gef.examples.shapes/plugin.properties
org.eclipse.gef.examples.shapes/src/org/eclipse/gef/examples/shapes/handler/ColorPaletteExpression.java
org.eclipse.gef.examples.shapes/src/org/eclipse/gef/examples/shapes/handler/ColorPaletteHandler.java
org.eclipse.gef.examples.shapes/src/org/eclipse/gef/examples/shapes/palette/ShapesColorPalette.java
org.eclipse.gef.tests/src/org/eclipse/gef/test/swtbot/ShapesDiagramTests.java
org.eclipse.gef.tests/src/org/eclipse/gef/test/swtbot/utils/SWTBotGefPalette.java
org.eclipse.gef/.settings/.api_filters
org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/PaletteColorUtil.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/DrawerEditPart.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/DrawerFigure.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/PaletteScrollBar.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/TemplateEditPart.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/ToolEntryEditPart.java
org.eclipse.gef/src/org/eclipse/gef/ui/palette/ColorPalette.java
org.eclipse.gef/src/org/eclipse/gef/ui/palette/DefaultColorPalette.java
org.eclipse.gef/src/org/eclipse/gef/ui/palette/PaletteViewer.java
org.eclipse.gef/src/org/eclipse/gef/ui/palette/editparts/PaletteEditPart.java

This defines a new ColorPalette interface that can be set in the PaletteViewer. The colors provided by this interface are then used in the palette figure for e.g. the tool entries.
Clients can extend the DefaultColorPalette to define their own colors and therefore change the look of the palette.

Make palette selection and hover colors customizable

---

org.eclipse.gef.examples.shapes/src/org/eclipse/gef/examples/shapes/handler/ColorProviderHandler.java
org.eclipse.gef.examples.shapes/src/org/eclipse/gef/examples/shapes/palette/ShapesColorProvider.java
org.eclipse.gef.tests/src/org/eclipse/gef/test/swtbot/ShapesDiagramTests.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/PaletteColorUtil.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/DrawerFigure.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/PaletteScrollBar.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/PinFigure.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/PinnablePaletteStackEditPart.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/PinnablePaletteStackFigure.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/SeparatorEditPart.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/palette/editparts/ToolbarEditPart.java
org.eclipse.gef/src/org/eclipse/gef/ui/palette/FlyoutPaletteComposite.java
org.eclipse.gef/src/org/eclipse/gef/ui/palette/PaletteColorProvider.java

This removes the following constants from PaletteColorUtil and reroutes their references to the PaletteColorProvider:
- WIDGET_BACKGROUND -> getButton()
- WIDGET_NORMAL_SHADOW -> getButtonDarker()
- WIDGET_DARK_SHADOW -> getButtonDarkest()
The "mixed" getButtonDarker() colors are created via the new method getButtonDarker(double), where the value describes the weight with which the color from getButton() color is mixed with getButtonDarker().
In addition, hover color for the PinFigure is calculated via the new method getHoverColor().
Both new methods are marked as final, as they are derived from other colors.

Make "button" colors used inside the palette configurable

---

CHANGELOG.md
org.eclipse.gef.tests/src/org/eclipse/gef/test/RulerLayoutTests.java
org.eclipse.gef/.settings/.api_filters
org.eclipse.gef/src/org/eclipse/gef/internal/ui/rulers/RulerEditPart.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/rulers/RulerFigure.java
org.eclipse.gef/src/org/eclipse/gef/rulers/RulerProvider.java

With this change the API of the RulerProvider class is extended with a custom dots per unit setting. This allows clients to use our default Ruler Figure adjusted to application specific resolutions and drawing scales.
As part of this change the RulerFigure was cleaned by splitting the paintFigure method in several methods for increased readability and maintainability.
Bugzilla entry: https://bugs.eclipse.org/bugs/show_bug.cgi?id=105493

Allow Rulers with a Custom Dots Per Unit Setting

---

org.eclipse.draw2d/src/org/eclipse/draw2d/EventListenerList.java

By separating the event listener types into individual lists and using a map the startup performance could be greatly reduced. It is for small number of EditParts (i.e., 2000) already twice as fast as the previous implementation.
Furthermore iterating through the event listeners is simpler and most probably also faster.
The work is based on the patch submitted by Iwan Birrer to the following Bugzilla entry:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=255534

Improve EventListenerList Performance Bugzilla #255534

---

org.eclipse.draw2d/src/org/eclipse/draw2d/EventListenerList.java

The ConcurrentLinkedDeque might lead to a deadlock in a multi-thread environment. This doesn't happen with a CopyOnWriteArrayList, as each write operation is done on a separate array.

Switch to CopyOnWriteArrayList in EventListenerList

---

pom.xml

Those features are automatically generated by Tycho and contain the source bundles of the binary feature they mirror.
It therefore doesn't make any sense to generate source features of the source features which currently leads to the warnings:
> [WARNING] The following referenced features have missing sources
> org.eclipse.draw2d.source_3.22.0.202411052148
> org.eclipse.gef.source_3.22.0.202411052148
> org.eclipse.zest.source_3.22.0.202411052148

Exclude "source" features from "tycho-source-plugin" execution

---

org.eclipse.gef.tests/src/org/eclipse/gef/test/GraphicalViewerTest.java
org.eclipse.gef/src/org/eclipse/gef/ui/actions/PasteTemplateAction.java
org.eclipse.gef/src/org/eclipse/gef/ui/actions/SelectionAction.java

The list returned by getSelectedEditParts() should be a view of the internal selection, similar to getSelectedObjects(). Meaning callers are able to modify by the selection by calling set(int,Object).
In order to reduce the chance of an undesirable ClassCastException, we only check whether the first element in the list is an EditPart, assuming that all remaining elements are as well. I.e. we don't expect a "mixed" selection of different types. This is similar to what has already been done in e.g. the DeleteAction or the MatchSizeAction.
This is a follow-up to 78c3fed3ced2c035c5a495a752523bb4b758a916.
Resolves https://github.com/eclipse-gef/gef-classic/issues/616

Restore ability to modify selection in GroupRequest within DeleteAction

---

Jenkinsfile
pom.xml

The SonarQube version that is used by Maven has been relocated, leading to a warning at the start of the build. Furthermore, the "consumer poms" that are automatically created by Tycho are flagged as "missing blame information", as they haven't been comitted and should thus not be scanned.

Update to latest SonarQube scanner and exclude generated poms

---

org.eclipse.gef/src/org/eclipse/gef/ui/actions/SelectionAction.java

- The return type cannot be changed from List<Object>  to List<?> without breaking client calling or override this protected method.
https://github.com/eclipse-gef/gef-classic/pull/617

Restore the return type of SelectionAction.getSelectedObjects()

---

promotion/pom.xml

This property is used in the "promot" profile, which is only used for the master build and thus it didn't cause any issues on the branch builds.
Amends 19e9ec3ecd20b8ca5a802561f840618e974f34f4

Change "tycho.version" to "tycho-version" in promotion pom.xml as well

---

Jenkinsfile

Main goal is to analyze what steps need to be taken to have the Jenkins build results like compiler warnings and Maven problems be published to the GitHub checks.

Publish build results from Jenkins to GitHub

---

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/DimensionTests.java
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/PointTests.java
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/RectangleTest.java
org.eclipse.draw2d/src/org/eclipse/draw2d/Label.java
org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/Transform.java

As long as the deprecated methods are not removed the tests should stay. However the warning is only distracting from other problems therefore it is removed.

Ignored warning of tests for deprecated methods

---

promotion/pom.xml

This module is only build on the "master" Jenkins build, which is why no error was thrown when raising the version of the parent pom.

Correct version of parent pom on "promotion" module

---

org.eclipse.gef.examples.digraph1/build.properties
org.eclipse.gef.examples.digraph2/build.properties
org.eclipse.gef.examples.flow/build.properties
org.eclipse.gef.examples.logic/build.properties
org.eclipse.gef.examples.shapes/build.properties
org.eclipse.gef.examples.text/build.properties
org.eclipse.gef.examples.ui.pde/src/org/eclipse/gef/examples/ui/pde/internal/wizards/ProjectUnzipperNewWizard.java
org.eclipse.zest.examples/.classpath

The build.properties src.inlucde entry had more entries then necessary. This was cleaned
Furthermore several warnings and issues reported by sonar have been fixed in the example creation wizard.

Fixed Examples build.properties

---

org.eclipse.draw2d.doc.isv/buildDoc.xml
org.eclipse.gef.doc.isv/buildDoc.xml
org.eclipse.zest.doc.isv/buildDoc.xml
pom.xml

Due to the new version of the maven-antrun-plugin, every echo instruction is treated as a warning.
See https://ant.apache.org/manual/Tasks/echo.html

Change Ant's echo log level from "Warning" to "Info"

---

CHANGELOG.md
org.eclipse.zest.core/META-INF/MANIFEST.MF
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/Graph.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/InternalLayoutContext.java
org.eclipse.zest.tests/.settings/.api_filters
org.eclipse.zest.tests/src/org/eclipse/zest/tests/GraphTests.java

With this change, invisible graph nodes and connections are ignored within the LayoutContext and therefore within the layout algorithms.
Note that as part of this change, the Zest styles are no longer set inside the Graph constructor, but via a separate setGraphStyle() method. This is because the constructor styles are also used for creating the underlying FigureCanvas, which would otherwise throw an exception due to the unsupported styles.
While it technically breaks compatibility, it is practically impossible to have used those styles up until now.
Fixes https://github.com/eclipse-gef/gef-classic/issues/608

Implement IGNORE_INVISIBLE_LAYOUT Zest Style for Zest 2.0

---

org.eclipse.gef.examples-feature/feature.xml
org.eclipse.gef.examples.digraph1/META-INF/MANIFEST.MF
org.eclipse.gef.examples.ui.pde/META-INF/MANIFEST.MF
org.eclipse.gef.repository/category.xml
org.eclipse.zest-feature/feature.xml
pom.xml

Primarily done to enable the baseline-check for those bundles, but also to make them available to users. This includes:
- org.eclipse.gef.examples.digraph1
- org.eclipse.gef.examples.digraph2
- org.eclipse.gef.examples.ui.capabilities
- org.eclipse.gef.examples.ui.pde
- org.eclipse.zest.examples.cloudio
- org.eclipse.zest.examples.layouts
- org.eclipse.zest.cloudio

Publish GEF/Zest examples and Zest CloudIO to update site

---

org.eclipse.draw2d/META-INF/MANIFEST.MF

The FigureCanvas class is using setScrollbarsMode(), which only exists since SWT 3.126, making this the minimum version Draw2D is compatible with.
Fixes https://github.com/eclipse-gef/gef-classic/issues/652

Raise lower bound on SWT for Draw2D

---

org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/AndGateFeedbackFigure.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/AndGateFigure.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/GateFigure.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/OrGateFeedbackFigure.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/OrGateFigure.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/OutputFigure.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/XOrGateFeedbackFigure.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/XOrGateFigure.java
org.eclipse.gef.tests/src/org/eclipse/gef/test/swtbot/LogicDiagramTests.java

Changes:
- Increased size of AND, OR, and XOR gates to double their original size
- Maintained original aspect ratios and proportions
- Note: Connection and anchor point alignments will be addressed in a follow-up PR
BEFORE:
AFTER:

Double size for AND,OR,XOR gates for better visibility

---

org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/GraphNode.java
org.eclipse.zest.examples/src/org/eclipse/zest/examples/layouts/ContainerResizeGraphSnippet.java
org.eclipse.zest.examples/src/org/eclipse/zest/examples/layouts/FisheyeGraphSnippet.java
org.eclipse.zest.examples/src/org/eclipse/zest/examples/swt/GraphSnippet6.java
org.eclipse.zest.examples/src/org/eclipse/zest/examples/swt/GraphSnippet9.java
org.eclipse.zest.examples/src/org/eclipse/zest/examples/swt/NestedGraphSnippet.java
org.eclipse.zest.examples/src/org/eclipse/zest/examples/swt/NestedGraphSnippet2.java
org.eclipse.zest.examples/src/org/eclipse/zest/examples/swt/ZoomSnippet.java

There are currently two ways the Zest styles for a graph node can be set: Either via the constructor or by calling the setNodeStyle() method.
Certain styles affect how the nodes are visualized and therefore, the underlying figure needs to be updated together with the node style. This currently only happens when the node is created. As a result, certain styles such as the NODES_HIDE_TEXT and NODES_FISHEYE are effectively ignored if retroactively added to a node.
With this change, the model figure is explicitly updated (which is also done when e.g. updating the font). Note that mixing SWT and Zest styles is usually not a good idea, as it introduces the risk in case they share one or more bits. Which is why the test snippets have been updated as well, to emphasize the use of setNodeStyle() …

Refresh Zest GraphNode figures if node style has been changed

---

org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/WireEditPart.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/WireEndpointEditPolicy.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/FigureFactory.java

This PR doubles the connection line width for the logic designer for better readability and aligns with the previous PRs that doubled the elements.
Before:
After:

Enlarging connection line width to enhance visual representation

---

org.eclipse.gef/src/org/eclipse/gef/dnd/TemplateTransferDropTargetListener.java

It was a bug in older ecj compiler that allowed to use instanceof patterns in Java 17 code.
Fixes https://github.com/eclipse-gef/gef-classic/issues/664

Don't use instanceof for null checks

---

org.eclipse.gef/src/org/eclipse/gef/ui/parts/AbstractEditPartViewer.java

This prevents ConcurrentModificationException on removing/adding listeners during selection change.
Fixes https://github.com/eclipse-gef/gef-classic/issues/663

Use ListenerList to avoid ConcurrentModificationException

---

org.eclipse.draw2d/src/org/eclipse/draw2d/AbstractImageFigure.java
org.eclipse.draw2d/src/org/eclipse/draw2d/ButtonGroup.java
org.eclipse.draw2d/src/org/eclipse/draw2d/ConnectionAnchorBase.java
org.eclipse.draw2d/src/org/eclipse/draw2d/PolylineConnection.java
org.eclipse.draw2d/src/org/eclipse/draw2d/UpdateManager.java
org.eclipse.draw2d/src/org/eclipse/draw2d/zoom/AbstractZoomManager.java
org.eclipse.gef.examples.text/src/org/eclipse/gef/examples/text/actions/StyleService.java
org.eclipse.gef/src/org/eclipse/gef/ui/palette/PaletteViewer.java
org.eclipse.gef/src/org/eclipse/gef/ui/parts/AbstractEditPartViewer.java
org.eclipse.zest.core/src/org/eclipse/zest/core/viewers/GraphViewer.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/Graph.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/HideNodeHelper.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/InternalLayoutContext.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/AbstractLayoutAlgorithm.java
org.eclipse.zest.layouts/src/org/eclipse/zest/layouts/algorithms/TreeLayoutObserver.java

This changes the list of listeners to a thread-safe implementation to avoid the ConcurrentModificationException when modifying this list while in the middle of handling an event.
Note that this also adapts 71f0c56301033bcf5ff5ba1261cdc2719d9bb391, in which the List of ISelectionChangedListeners was changed to a ListenerList, thus breaking API on the protected field.

Update all lists of listeners to use CopyOnWriteArrayList

---

org.eclipse.gef.examples.flow/src/org/eclipse/gef/examples/flow/ui/FlowEditor.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/LogicEditor.java
org.eclipse.gef.examples.shapes/src/org/eclipse/gef/examples/shapes/ShapesEditor.java
org.eclipse.gef/src/org/eclipse/gef/EditPartViewer.java
org.eclipse.gef/src/org/eclipse/gef/dnd/AbstractTransferDragSourceListener.java
org.eclipse.gef/src/org/eclipse/gef/dnd/AbstractTransferDropTargetListener.java
org.eclipse.gef/src/org/eclipse/gef/dnd/DelegatingDragAdapter.java
org.eclipse.gef/src/org/eclipse/gef/dnd/DelegatingDropAdapter.java
org.eclipse.gef/src/org/eclipse/gef/dnd/TemplateTransferDragSourceListener.java
org.eclipse.gef/src/org/eclipse/gef/dnd/TransferDragSourceListener.java
org.eclipse.gef/src/org/eclipse/gef/dnd/TransferDropTargetListener.java
org.eclipse.gef/src/org/eclipse/gef/ui/parts/AbstractEditPartViewer.java
org.eclipse.gef/src/org/eclipse/gef/ui/parts/TreeViewer.java
org.eclipse.gef/src/org/eclipse/gef/ui/parts/TreeViewerTransferDragListener.java

The TransferDragSourceListener and TransferDropTargetListener are effecitively equivalent to their JFace counterpart and should be used instead.

Deprecate transfer listeners for removal

---

org.eclipse.gef.examples.flow/src/org/eclipse/gef/examples/flow/ui/FlowEditor.java
org.eclipse.gef.tests/src/org/eclipse/gef/test/CommandStackTest.java
org.eclipse.gef/src/org/eclipse/gef/commands/CommandStack.java
org.eclipse.gef/src/org/eclipse/gef/commands/CommandStackListener.java
org.eclipse.gef/src/org/eclipse/gef/ui/parts/GraphicalEditor.java

This interface has been deprecated a long time ago in favor of the CommandStackEventListener.

Deprecate CommandStackListener for removal

---

org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/CircuitBorder.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/CircuitFigure.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/LEDFeedbackFigure.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/LEDFigure.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/LogicFlowBorder.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/model/LED.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/model/LogicDiagram.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/model/LogicDiagramFactory.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/model/LogicLabel.java
org.eclipse.gef.tests/src/org/eclipse/gef/test/swtbot/LogicDiagramTests.java

- Those changes would complete the double sizing of all components for better visibility. 
- The other changes were done before in #658 and #657)

Double size of remaining components of logic editor

---

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/PointTests.java
org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/Point.java
org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/PrecisionPoint.java

getDistanceOrthogonal is used in several places in GEF. There is no straight forward replacement. To reason for deprecation is precision of subclasses. As there is only one subclass with higher precision an improved version of that method is added there. Furthermore the impact on precision will anyhow only happen if both sides are PrecisionPoints.
https://github.com/eclipse-gef/gef-classic/issues/21

Remove deprecation from getDistanceOrthogonal #21

---

org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/LEDFigure.java

This PR addresses two issues with the LED text display:
- **Misaligned text**: Introduced dynamic positioning (including  padding and offset constants) to ensure the text is centered within the display rectangle. 
- **Oversized font**: Reduced the font size from 38 to 23 to ensure the displayed number does not appear too large.
Before: (on 3840x2160 resolution, 150%scaling, Windows)
After:

Center LED text in display and adjust font size

---

org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/AndGateFigure.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/LogicColorConstants.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/OrGateFigure.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/XOrGateFigure.java

This PR proposes a more modern design for the gates of the logic designer:
- Introduced thicker outlines for improved clarity.
- Added a new shared outline color (dark gray) to replace the monotone black color.
- Rounded edges in the AND gate for a softer and modernized appearance.
- Updated colors: The AND gate uses a soft red, the OR gate azure blue and the XOR gate a more vibrant yellow.
- Adjusted offsets, and clipping logic due to the new line width.
Follow-up PRs will be: 
- modern design of the reamining components 
- adjustment of the corresponding feedback figures 
Before:
After:

Modernize Gate Figures (AND, OR, XOR)

---

org.eclipse.draw2d.examples/src/org/eclipse/draw2d/examples/text/BidiBlockExample.java
org.eclipse.draw2d.examples/src/org/eclipse/draw2d/examples/text/CaretExample.java
org.eclipse.draw2d.examples/src/org/eclipse/draw2d/examples/text/TestBorder.java
org.eclipse.draw2d.examples/src/org/eclipse/draw2d/examples/text/TextSurroundingFigureExample.java

The other examples were migrated to EPL-1 with
c98396ff6e009fd91d4c817ab18ea28d008c0fe9 and later migrated to EPL-2 with 0b1a1058d93c981633af7c1cead6b4d579ab2898. Those files being missed is very likely simply an oversight.

Update license header for remaining examples from CPL to EPL-2

---

org.eclipse.zest.examples/src/org/eclipse/zest/examples/layouts/CustomLayout.java
org.eclipse.zest.examples/src/org/eclipse/zest/examples/layouts/DAGExample.java
org.eclipse.zest.examples/src/org/eclipse/zest/examples/layouts/RadialLayoutExample.java
org.eclipse.zest.examples/src/org/eclipse/zest/examples/layouts/SpaceTreeBuilding.java
org.eclipse.zest.examples/src/org/eclipse/zest/examples/layouts/SpaceTreeExample.java
org.eclipse.zest.examples/src/org/eclipse/zest/examples/layouts/TreeLayoutExample.java

The snippets we created as part of the Google Summer of Code 2009 by Mateusz Matela and Ian Bull:
https://wiki.eclipse.org/Tree_Views_for_Zest
Copyright headers have been taken and adapted from the corresponding patch attached to https://bugs.eclipse.org/bugs/show_bug.cgi?id=277534

Restore license headers for Zest layout snippets

---

org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/dnd/TextTransferDropTargetListener.java
org.eclipse.gef/src/org/eclipse/gef/tools/AbstractConnectionCreationTool.java
org.eclipse.gef/src/org/eclipse/gef/tools/ConnectionCreationTool.java
org.eclipse.gef/src/org/eclipse/gef/tools/ConnectionEndpointTracker.java
org.eclipse.gef/src/org/eclipse/gef/tools/CreationTool.java
org.eclipse.gef/src/org/eclipse/gef/tools/DragEditPartsTracker.java
org.eclipse.gef/src/org/eclipse/gef/tools/SelectionTool.java
org.eclipse.gef/src/org/eclipse/gef/ui/parts/TreeViewerTransferDropListener.java

In order to reduce the required casts and to make the code's intention clearer tools which create and expect certain target request types are explicitly casted.

Provide concrete Request Types for getTargetRequest

---

org.eclipse.zest.examples/src/org/eclipse/zest/examples/swt/AnimationSnippet.java
org.eclipse.zest.examples/src/org/eclipse/zest/examples/swt/CustomLayout.java

Both examples were created with ccfe91da08029fb5f05f4a89a7cda27f611b72c1 by Ian Bull. Given that he also created the other examples within a close time frame, it is likely that they should have the same license header.

Add missing license header for AnimationSnippet and CustomLayout

---

org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/HideNodeHelper.java
org.eclipse.zest.core/src/org/eclipse/zest/core/widgets/internal/NodeSearchDialog.java
org.eclipse.zest.examples/src/org/eclipse/zest/examples/swt/GraphSnippet14.java

The NodeSearchDialog class was created by Sebastian Hollersbacher with e890b56b744fc68dbb3ac6efaf66e9bff2590e90 as part of the "Hide Node" feature.
Furthermore, the related HideNodeHelper and GraphSnippet14 have been updated to also contain the SPDX license identifier.

Add missing license header to NodeSearchDialog

---

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/PointTests.java
org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/ShapeTest.java
org.eclipse.gef.tests/src/org/eclipse/gef/test/CommandStackTest.java

- org.eclipse.draw2d.test.ShapeTest
-  Created in 2011 with e8c84cd0f84e304fbb195789d5e6f3557de60dd8.
- org.eclipse.draw2d.test.PointTests
-  Created in 2011 with c6840ee2b2a64e7fc6fad4d03fb4602b21f54bb4.
- org.eclipse.gef.test.CommandStackTest
-  Created in 2015 with 67aae64c367abbed4e4bd37c1aafad9da5c6bd63.
All three classes were created by Alexander Nyßen. Both the email-adress used in the 2015 commit, as well as similar commits in the 2011 commits indicates that those changes were done as part of his work at Itemis.

Add missing header to GEF/Draw2D source files

---

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/RectangleTest.java
org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/Rectangle.java

In case two rectangles touch horizontally or vertically, the x and y coordinates should be preserved.
Closes https://github.com/eclipse-gef/gef-classic/issues/689

Restore original intersect() logic in case two rectangles touch

---

org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/OrGateFigure.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/XOrGateFigure.java

When rendering the XOR gate's bottom arc, there was a visual artifact where the filled oval would slightly overflow beyond the border. 
See https://github.com/eclipse-gef/gef-classic/pull/676 
- This PR fixes this issue (thanks a lot to @ptziegler and @azoitl for pointing this out)
- Additionally, antialiasing has been enabled to smooth out the border and edges 
BEFORE:
AFTER:

Fix oval rendering artifacts in OR+XOR gate

---

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/AdvancedGraphicsTests.java

Due to changes in SWT, the underlying Cairo surface of an SWT image is no longer initialized with the system font options.
If a string is drawn without ever calling setTextAntialias(), the Cairo default is used. If this method is called with SWT.DEFAULT, the system default is used. Because those values are not guaranteed to be equal, this may lead to visual artifacts.
See https://github.com/eclipse-gef/gef-classic/issues/696

Disable testAntialias() test when running on Linux

---

org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/LEDFigure.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/model/LED.java
org.eclipse.gef.tests/src/org/eclipse/gef/test/swtbot/LogicDiagramTests.java

This PR reduces the LED figure size and optimizes display proportions. 
The reason for this is that the LED appeared proportionally just too large when comparing it with the gates. 
To ensure good visibility of the displayed numbers the font size was not changed
- Reduce overall LED size by 25% (122x94 -> 92x71)
- Adjust all components proportionally (connectors, gaps, handles)
- Enlarge display rectangle for better readability
- Maintain font size for clear number display
- Update model's DEFAULT_SIZE to match figure dimensions
BEFORE:
AFTER:

Reduce LED figure size and optimize display proportions

---

org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/WireEditPart.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/edit/WireEndpointEditPolicy.java
org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/FigureFactory.java

Similar to https://github.com/eclipse-gef/gef-classic/pull/661, this PR enlarge the connection width again since it turned out it was proportionally still too small before (especially with comparting it to the connectors of the gates)
BEFORE:
AFTER:

Enlarging connection line width again

---

org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/figures/AndGateFigure.java

This PR increases the terminal input length of the AND Gate since they were shorter than the other gates.
BEFORE:
AFTER:

Increase input terminal lengths for AND Gate

---

org.eclipse.draw2d.examples/src/org/eclipse/draw2d/examples/printing/PrintExample.java

If no default printer is defined, clicking on the "Print" button fails with an SWT error. To avoid this (and to also avoid accidentally printing to a real printer), a print dialog is opened to let the user select the target.
This also replaces the MouseListener with a MouseAdapter, to get rid of the empty listener methods.

Cleanup Draw2D PrintExample

---

CHANGELOG.md
org.eclipse.draw2d/META-INF/MANIFEST.MF
org.eclipse.draw2d/src/org/eclipse/draw2d/PrintFigureOperation.java
org.eclipse.draw2d/src/org/eclipse/draw2d/PrintOperation.java

This removes the dependency from PrintOperation to PrintGraphics, allowing subclasses to inject their own drawing backend by overriding the createGraphics(SWTGraphics,Printer) method.
The following methods have been deprecated, with drop-in replacements available that work on plain Graphics objects:
- PrinterGraphics getFreshPrinterGraphics()
- setupGraphicsForPage(PrinterGraphics)

Generalize PrintOperation to handle generic Graphics implementations

---

org.eclipse.gef/src/org/eclipse/gef/internal/ui/rulers/RulerFigure.java

The fix for  #710.
The main fix removes the use of temporary rotated Image for vertical marks. The result before and after on 200% display on a Windows machine is the following:
I've also removed the background fill under text marks performed using graphics.fillRectangle(forbiddenZone). I believe that this is unnecessary and also draws over the bottom/right border as can be also seen in before and after images. To observe this better click on each image and check the border under the digits for horizontal ruler, and to the right for vertical ruler.
The final tweak is that I've enabled text aliasing for RulerFigure. Text aliasing works by default on Linux and macOS, but is needed to be enabled explicitly on Windows. These are before and after results:
The difference can only be clearly …

Fixes ruler issues on HiDPI displays #710

---

org.eclipse.draw2d.doc.isv/javadocOptions.txt
org.eclipse.gef.doc.isv/javadocOptions.txt
org.eclipse.zest.doc.isv/javadocOptions.txt

Fixes: Error fetching URL: https://docs.oracle.com/en/java/javase/17/

Update JavaDoc copyright to 2025 and fix invalid URL to JDK docs

---

Jenkinsfile

The quality gate causes PRs to fail that e.g. introduce new compiler warnings.

Upload compiler warnings to Jenkins and enable quality gate

---

org.eclipse.gef/.settings/.api_filters

The ZoomListener has been removed in the previous release, so the accompanying filters are no longer necessary.

Remove obsolete API filters

---

org.eclipse.draw2d/src/org/eclipse/draw2d/ToolTipHelper.java

This PR adapts the calculation to correct tooltip positions. With monitor specific scaling added for the windows implementation of SWT Display#getClientArea is currently no reliable source to calculate whether the tooltip is inside the display bounds. It is replaced with Monitor#getClientArea instead.
Setup similar to:
- Windows
- Multiple monitors with different zoom settings, most left monitor is primary monitor
- monitor-specific UI scaling activated
Move the IDE to the right monitor and position it so e.g. the tooltip of the Palette would be outside of the monitor -> without this PR the tooltip will be either positioned completely outside of the view of way more left as expected
In my opinion it makes more sense to position the tooltips always completely on the current monitor anyway …

Use monitor client area for tool tip positions

---

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/AdvancedGraphicsTests.java

The problematic revision in SWT has been reverted. Closes https://github.com/eclipse-gef/gef-classic/issues/696

Re-enable AdvancedGraphicsTest.testAntialias() for GTK

---

CHANGELOG.md
org.eclipse.gef/src/org/eclipse/gef/ui/palette/FlyoutPaletteComposite.java
org.eclipse.gef/src/org/eclipse/gef/ui/parts/GraphicalEditorWithFlyoutPalette.java

The Preferences class has been deprecated since forever with the IEclipsePreferences as its replacement. Instances of this type can be used via the ScopedPreferenceStore, but other implementations are also permitted.

Deprecate createFlyoutPreferences(Preferences) for removal

---

.github/workflows/maven.yml
CHANGELOG.md
README.md
org.eclipse.gef/META-INF/MANIFEST.MF
org.eclipse.gef/src/org/eclipse/gef/ui/palette/FlyoutPaletteComposite.java
pom.xml

From: https://github.com/eclipse-platform/eclipse.platform.ui/issues/3047#issuecomment-2987267494
> The issue is rooted in the SVG image rasterization. When the
> rasterization result is converted into SWT image data, that image data
> is created with a 32bit data palette. This leads to a difference in
> the image data used for the cursors, as they originally contained 24
> bit data (not having an alpha channel).
With the 2024-09, those constants have been deprecated and replaced with equivalent cursors that don't require a mask.

Migrate to new DND cursors and raise minimum requirement to 2024-09

---

org.eclipse.gef/src/org/eclipse/gef/SharedCursors.java
org.eclipse.gef/src/org/eclipse/gef/internal/InternalGEFPlugin.java
org.eclipse.gef/src/org/eclipse/gef/ui/palette/FlyoutPaletteComposite.java

This change ensures that cursor images scale appropriately based on the display's zoom level .
Steps to reproduce
Steps to reproduce cursors  are mentioned in  https://github.com/vi-eclipse/Eclipse-Platform/issues/331 
> To test with GEF, one should check out the GEF Classic repository: https://github.com/eclipse-gef/gef-classic Then import the `org.eclipse.draw2d`, `org.eclipse.gef` and the `org.eclipse.gef.examples.logic` (the latter for testing) to your Eclipse development workspace and add them to the product you are testing. With the "New" wizard, you can create a logic example to test out the cursors via inserting elements, dragging and dropping etc. (see also [this issue](https://github.com/eclipse-platform/eclipse.platform.ui/issues/3047) for an example): …

Cursors in GEF uses ImageDataProvider instead of ImageData

---

org.eclipse.gef/src/org/eclipse/gef/SharedCursors.java
org.eclipse.gef/src/org/eclipse/gef/internal/InternalCursor.java
org.eclipse.gef/src/org/eclipse/gef/internal/icons/plug-cursor.svg
org.eclipse.gef/src/org/eclipse/gef/internal/icons/plugnot-cursor.svg
org.eclipse.gef/src/org/eclipse/gef/internal/icons/tree_add-cursor.svg
org.eclipse.gef/src/org/eclipse/gef/internal/icons/tree_move-cursor.svg

The way cursors are rendered on Windows is that regardless of the zoom level, the stroke width of the cursor is always 1px wide. When using an SVG, this would normally be achieved by setting the "non-scaling-stroke" vector effect.
Sadly, this effect is not supported by the jSVG rasterizer that is used by SWT and as a result, the stroke width is scaled proportionally to the zoom level. I.e. 1px at 100%, 2px at 200% and so on.
To work around this limitation, the cursor is separated from the remaining components and constructed on-the-fly, The complete cursor is then a composite of the SVG and this generated cursor.

Separate cursor icon from its decoration for the shared cursors.

---

Jenkinsfile
pom.xml

This change updates the plugin from 5.0.0.4389 to 5.1.0.4751 and also moves part of its configuration from the Jenkinsfile to the parent pom.
In order to avoid the "'sonar.java.binaries' is empty" warning, this property is now initialized with the project-relative "target/classes" path.

Cleanup configuration of sonar-maven-plugin

---

org.eclipse.draw2d.tests/src/org/eclipse/draw2d/test/LabelTest.java

This corrects a minor oversight introduced with
2e46a0b3f2d40e5777c864b1f5a2d069e4e4b988. One of the tests creates a new Font, but never disposes it, even though an identical Font is created that is disposed once the test finishes.

Avoid using non-disposed resources in LabelTest

---

org.eclipse.draw2d.doc.isv/guide-src/connections.adoc
org.eclipse.draw2d.doc.isv/guide-src/coordinates.adoc
org.eclipse.draw2d.doc.isv/guide-src/extensions.adoc
org.eclipse.draw2d.doc.isv/guide-src/guide.adoc
org.eclipse.draw2d.doc.isv/guide-src/hittest.adoc
org.eclipse.draw2d.doc.isv/guide-src/layout.adoc
org.eclipse.draw2d.doc.isv/guide-src/migration-guide.adoc
org.eclipse.draw2d.doc.isv/guide-src/overview.adoc
org.eclipse.draw2d.doc.isv/guide-src/painting.adoc
org.eclipse.gef.doc.isv/guide-src/guide.adoc
org.eclipse.gef.doc.isv/guide-src/index.adoc
org.eclipse.zest.doc.isv/guide-src/graph.adoc
org.eclipse.zest.doc.isv/guide-src/index.adoc
org.eclipse.zest.doc.isv/guide-src/overview.adoc

- When viewing the documentation from GittHub, the images are not shown as they are contained in the "guide" folder, rather than the "guide-src" folder.
- References to other documents use the name of the generated HTML file, not the AsciiDoc file. By using .adoc, this is automatically updated during the conversion.

Fix hyperlinks and relative image paths of documentation

---

org.eclipse.draw2d.doc.isv/guide-src/guide.adoc
org.eclipse.gef.doc.isv/about.html
org.eclipse.gef.doc.isv/guide-src/guide.adoc
org.eclipse.gef.doc.isv/guide-src/index.adoc
org.eclipse.gef.doc.isv/topics_Guide.xml

This cleans up some artifacts that remained when the HTML document was converted to AsciiDoc, the broken about.html file and the broken HREF attributes in the topics xml file.

Minor cleanup of online help

---

org.eclipse.draw2d.examples/sandbox/swt/bugs/Bug81467.java
org.eclipse.gef/src/org/eclipse/gef/internal/ui/rulers/RulerFigure.java

Having the scale factor being based on the screen DPI leads to unexpected result. Having a screen dpi independent factor leads to consistent results.
- Run this example 
- See if it doesn't break after the current changes. 
```
import org.eclipse.swt.layout.FillLayout;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Shell;
import org.eclipse.draw2d.FigureCanvas;
import org.eclipse.draw2d.Graphics;
import org.eclipse.draw2d.LightweightSystem;
import org.eclipse.draw2d.SWTGraphics;
import org.eclipse.draw2d.geometry.Dimension;
import org.eclipse.draw2d.geometry.Rectangle;
import org.eclipse.gef.rulers.RulerProvider;
public class RulerFigureExample {
public static void main(String[] args) {
Display display = new Display();
Shell shell = new Shell(display); …
```

Replacing usages of Device#getDPI

---

org.eclipse.gef/src/org/eclipse/gef/ui/parts/GraphicalEditor.java

GraphicalEditor still used the deprecated commandstack listener API. With previous work the new api was added now also the registration is moved.
Addresses: https://github.com/eclipse-gef/gef-classic/issues/21

GraphicalEditor registers for CommandStackEvents #21

---

org.eclipse.draw2d/src/org/eclipse/draw2d/graph/BreakCycles.java
org.eclipse.draw2d/src/org/eclipse/draw2d/graph/CompoundBreakCycles.java
org.eclipse.draw2d/src/org/eclipse/draw2d/graph/Edge.java
org.eclipse.draw2d/src/org/eclipse/draw2d/graph/RouteEdges.java
org.eclipse.draw2d/src/org/eclipse/draw2d/graph/TransposeMetrics.java
org.eclipse.draw2d/src/org/eclipse/draw2d/graph/VirtualNodeCreation.java

Those field has been marked as deprecated since forever and is only referenced within the same package and can therefore be made package-private (or private) in a future release.
The "removal" warning needs to be suppressed, wherever this field is referenced.
Contributes to https://github.com/eclipse-gef/gef-classic/pull/778

Mark deprecated fields in Edge as "forRemoval"

---

org.eclipse.draw2d/src/org/eclipse/draw2d/geometry/PrecisionGeometry.java

The setScale(...) method accepting the mode as integer has been deprecated with Java 9. Given that Draw2D requires at least Java 17, we can simply use the drop-in replacement via the RoundingMode enum.
Contributes to https://github.com/eclipse-gef/gef-classic/pull/778

Avoid usage of deprecated rounding mode in BigDecimal

---

org.eclipse.draw2d/src/org/eclipse/draw2d/internal/Messages.java
org.eclipse.draw2d/src/org/eclipse/draw2d/internal/Messages.properties
org.eclipse.draw2d/src/org/eclipse/draw2d/zoom/AbstractZoomManager.java

In e.g. Turkish, the percent sign is supposed to be on the left side of the number. This change converts the format used for showing the zoom level to an i18n string, so that language packs can account for such differences.
Closes https://bugs.eclipse.org/bugs/show_bug.cgi?id=205221

Bug 205221 - ZoomManager does not support turkish properly

---

org.eclipse.gef/src/org/eclipse/gef/requests/CreateRequest.java

The class CreateRequest in the org.eclipse.gef.requests does not extend the LocationRequest class from the same package, instead of subclassing it simply reimplements the whole functionality.
Closes https://bugs.eclipse.org/bugs/show_bug.cgi?id=381171

Bug 381171 - CreateRequest should extend LocationRequest

---

org.eclipse.gef/META-INF/MANIFEST.MF

With 1f5cf49c0a0750c70039d138651e79d5483dd3f7, the type hierarchy of the CreateRequest was changed. This requires a minor version increase.

Minor version bump for org.eclipse.gef

---

org.eclipse.draw2d/src/org/eclipse/draw2d/IScalablePane.java

This PR replaces the scaling in IScalablePane#getScaledRect for width and height of a Rectangle with using Rectangle#scale instead.
In https://github.com/eclipse-gef/gef-classic/pull/770 I stumbled open the issue. If you execute the following small Snippet
```
public class LabelIssueExample {
public static void main(String[] args) {
Shell shell = new Shell();
shell.setSize(400, 400);
shell.setLayout(new FillLayout());
FigureCanvas canvas = new FigureCanvas(shell, SWT.NONE, new LightweightSystem());
Figure root = new Figure();
root.setLayoutManager(new ListLayout());
ScalableLayeredPane layeredPane = new ScalableLayeredPane(false);
layeredPane.setScale(1.5);
Label label = new Label("Representing a half adder");
root.add(layeredPane);
layeredPane.add(label); …
```

Use Rectangle#scale in IScalablePane#getScaledRect

---

org.eclipse.gef.examples.logic/src/org/eclipse/gef/examples/logicdesigner/LogicEditor.java
org.eclipse.gef.examples.shapes/src/org/eclipse/gef/examples/shapes/ShapesEditor.java
org.eclipse.gef.examples.text/src/org/eclipse/gef/examples/text/TextEditor.java

The example editors override the deprecated commandStackChanged() method to manage the "dirty" flag of the editor. For backwards-compatibility, this method is call by the non-deprecated stackChanged method.
Contributes to https://github.com/eclipse-gef/gef-classic/pull/778

Remove usage of deprecated CommandStackListener in example editors

---

org.eclipse.draw2d/src/org/eclipse/draw2d/PopUpHelper.java

When the auto-scaling property is set, a ScalableLayeredPane is injected
between the root figure and its contents.
The issue with this approach is that the contents is also stored as a
local variable of the LightweightSystem class, which is no longer
updated and therefore always null.
This pane is now embedded in a custom RootFigure subclass.

Simplify creation of PopupHelper LWS when Draw2D autoscaling is enabled

---

org.eclipse.draw2d/src/org/eclipse/draw2d/FigureUtilities.java

This reverts the changes done to the FigureUtilities class that was done with 2cb016edf26332580c2dd2925656ebf4fcc5577e, as it introduces rounding errors at 100% zoom.

Don't set "advanced mode" for FigureUtilities GC

---

org.eclipse.draw2d/src/org/eclipse/draw2d/PopUpHelper.java

This is a follow-up to 4b38172a5fc7aff628a73eb9172cff7aa6c38d78, where a custom RootFigure class was created, which injects a ScalableLayeredPane between itself and its content.
The add() method was already overridden to add any additional children to the scalable figure. One also needs to override the getChildren() method to delegate to the same figure.

Override getChildren() in ScalableRootFigure of PopUpHelper

---

org.eclipse.gef/src/org/eclipse/gef/internal/InternalGEFPlugin.java
org.eclipse.gef/src/org/eclipse/gef/internal/InternalImages.java
org.eclipse.gef/src/org/eclipse/gef/ui/actions/AlignmentAction.java
org.eclipse.gef/src/org/eclipse/gef/ui/actions/AlignmentRetargetAction.java
org.eclipse.gef/src/org/eclipse/gef/ui/actions/MatchHeightAction.java
org.eclipse.gef/src/org/eclipse/gef/ui/actions/MatchHeightRetargetAction.java
org.eclipse.gef/src/org/eclipse/gef/ui/actions/MatchSizeAction.java
org.eclipse.gef/src/org/eclipse/gef/ui/actions/MatchSizeRetargetAction.java
org.eclipse.gef/src/org/eclipse/gef/ui/actions/MatchWidthAction.java
org.eclipse.gef/src/org/eclipse/gef/ui/actions/MatchWidthRetargetAction.java
org.eclipse.gef/src/org/eclipse/gef/ui/palette/customize/PaletteCustomizerDialog.java

SWT version 3.130.0 or newer is able to automatically generate a "disabled" icon. If such a version is used, it is no longer necessary to explicitly set it for e.g. an action.
In short: If SWT < 3.130 is used, both "enabled" and "disabled" icons are set, otherwise only the "enabled" icon is set.
Closes https://github.com/eclipse-gef/gef-classic/issues/732

Use auto-generated "disabled" icon when supported by SWT
